/*
 * listAndTestsJPanel.java
 *
 * Created on 25 de septiembre de 2008, 11:39
 */

package code.google.com.p.ontologytesting.gui;

import code.google.com.p.ontologytesting.gui.auxiliarclasess.ButtonTabComponent;
import code.google.com.p.ontologytesting.gui.menupanels.ListarTestsJPanel;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author  sara.garcia
 */
public class ListAndTestsJPanel extends javax.swing.JPanel {

    private static ListAndTestsJPanel listAndTest = null;
 
    private ListAndTestsJPanel() {
        initComponents();
        testsScrollPane.getVerticalScrollBar().setUnitIncrement(5);
        this.listTestPanel.setLayout(new BorderLayout());
        this.splitPane.setDividerLocation(235);
    }
 
    private synchronized static void createListAndTestPanel() {
        if (listAndTest == null) { 
            listAndTest = new ListAndTestsJPanel();
        }
    }
 
    public static ListAndTestsJPanel getInstance() {
        if (listAndTest == null) createListAndTestPanel();
        return listAndTest;
    }
    
    public void aniadirTest(JPanel panel, String name){
        contentTabbedPane.add(panel);
        contentTabbedPane.setTitleAt(contentTabbedPane.getTabCount()-1, name);
        initTabComponent(contentTabbedPane.getTabCount()-1);
        contentTabbedPane.setTabLayoutPolicy(JTabbedPane.WRAP_TAB_LAYOUT);
        contentTabbedPane.setSelectedIndex(contentTabbedPane.getTabCount()-1);
        contentTabbedPane.validate();    
    }
    
    public void eliminarTests(){
        contentTabbedPane.removeAll();
        contentTabbedPane.validate();
    }
    
    private void initTabComponent(int i) {
        contentTabbedPane.setTabComponentAt(i,new ButtonTabComponent(contentTabbedPane,false,false));
    }
    
    public void aniadirLista(ListarTestsJPanel lista){
         this.listTestPanel.add(lista,BorderLayout.CENTER); 
         this.validate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        listTestPanel = new javax.swing.JPanel();
        testsScrollPane = new javax.swing.JScrollPane();
        testsPanel = new javax.swing.JPanel();
        contentTabbedPane = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        splitPane.setDividerSize(7);
        splitPane.setOneTouchExpandable(true);

        javax.swing.GroupLayout listTestPanelLayout = new javax.swing.GroupLayout(listTestPanel);
        listTestPanel.setLayout(listTestPanelLayout);
        listTestPanelLayout.setHorizontalGroup(
            listTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        listTestPanelLayout.setVerticalGroup(
            listTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        splitPane.setLeftComponent(listTestPanel);

        testsPanel.setLayout(new java.awt.BorderLayout());
        testsPanel.add(contentTabbedPane, java.awt.BorderLayout.CENTER);

        testsScrollPane.setViewportView(testsPanel);

        splitPane.setRightComponent(testsScrollPane);

        add(splitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane contentTabbedPane;
    private javax.swing.JPanel listTestPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel testsPanel;
    private javax.swing.JScrollPane testsScrollPane;
    // End of variables declaration//GEN-END:variables


}
