/*
 * HelpJDialog.java
 *
 * Created on 25 de junio de 2008, 12:28
 */

package code.google.com.p.ontologytesting.gui.auxiliarpanels;

/**
 *
 * @author  sara.garcia
 */
public class HelpJDialog extends javax.swing.JDialog {

    /** Creates new form HelpJDialog */
    public HelpJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setModal(true);
        String help = generarTextoAyuda();
        helpEditorPane.setContentType("text/html");
        helpEditorPane.setText(help);
        helpEditorPane.setEditable(false);
        this.setTitle("Documentación de Ayuda");
    }

    private String generarTextoAyuda() {
        String help="<html>" +
                "<h><b>TEST DE INSTANCIACION</h></b><br><br>" +
                "Este test consiste en deducir si dado un individuo, " +
                "éste pertenece a una clase.<br><br>" +
                "Ejemplo:<br>" +
                "<b>Consulta: </b>Wife,marry <br> <b>Resultado esperado: </b>True<br><br>" +
                "En este caso el test no fallaría, ya que el individuo" +
                " 'marry' aparece definido como Wife en el conjunto de instancias " +
                "de la ontología. <br><br>" +
                "<h><b>TEST DE RECUPERACION</h></b><br><br>" +
                "Este test deduce, dada una clase, todos los individuos que " +
                "pertenecen a dicha clase (todos los individuos que son instancias " +
                "de ese concepto).<br><br>" +
                "Ejemplo:<br>" +
                "<b>Consulta: </b>Wife <br> <b>Resultado esperado: </b>marry,lee<br><br>" +
                "En este caso el test no fallaría, ya que para la clase 'Wife'" +
                " todos los individuos que le pertenecen son los contemplados" +
                "'marry,lee'.<br><br>" +
                "<h><b>TEST DE REALIZACION</h></b><br><br>" +
                "Este test deduce, dado un individuo, cual es la clase más exacta " +
                "o específica a la que pertenece (dado un individuo, encuentra el concepto " +
                "más específico que lo contiene).<br><br>" +
                "Ejemplo:<br>" +
                "<b>Consulta: </b>marry <br> <b>Resultado esperado: </b>Wife<br><br>" +
                "En este caso el test no fallaria, ya que la clase mas especifica que" +
                "contiene al individuo 'marry' es 'Wife'.<br><br>" +
                "<h><b>TEST DE SATISFACTIBILIDAD</h></b><br><br>" +
                "Este test consiste en deducir si una nueva clase puede ser añadida a la " +
                "ontologia sin que entre en conflicto con el conjunto de instancias" +
                "ya definido para esa ontologia.<br><br>" +
                "Ejemplo:<br>" +
                "<b>Consulta: </b>sara,Wife <br> <b>Resultado esperado: </b>True<br><br>" +
                "En este caso el test no fallaría, ya que el individuo" +
                " 'sara' no estaba aun definido en la ontologia. <br><br>" +
                "<h><b>TEST DE CLASIFICACION</h></b><br><br>" +
                "Este test deduce dado un individuo, todas las clases a las que pertenece<br><br>" +
                "Ejemplo:<br>" +
                "<b>Consulta: </b>marry <br> <b>Resultado esperado: </b>Wife,Female,Person<br><br>" +
                "En este caso el test no fallaría, ya que todas las clases a las que puede" +
                " pertenecer 'marry' son las especificadas. <br><br>" +
                "</html>";
        return help;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        helpEditorPane = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(helpEditorPane);

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
            .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPane;
    private javax.swing.JEditorPane helpEditorPane;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
