/*
 * listAndTestsJPanel.java
 *
 * Created on 25 de septiembre de 2008, 11:39
 */

package code.google.com.p.ontologytesting.guiNew;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author  sara.garcia
 */
public class ListAndTestsJPanel extends javax.swing.JPanel {

    private JSplitPane splitPane;
    private JScrollPane testsPanel;
    private JPanel listaPanel;
    
    /** Creates new form listAndTestsJPanel */
    public ListAndTestsJPanel(JPanel panel) {
        initComponents();
        this.setLayout(new BorderLayout());
        testsPanel = new JScrollPane(panel);
        this.setTestsPanel(testsPanel);
        listaPanel = new ListarTestsJPanel();
        this.setListaPanel(listaPanel);
        splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT,getListaPanel(),getTestsPanel());
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerLocation(290);
        this.add(splitPane,BorderLayout.CENTER);
    }
    
    public ListAndTestsJPanel() {
        initComponents();
        this.setLayout(new BorderLayout());
        testsPanel = new JScrollPane();
        listaPanel = new ListarTestsJPanel();
        splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT,getListaPanel(),getTestsPanel());
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerLocation(290);
        this.add(splitPane,BorderLayout.CENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    public JPanel getListaPanel() {
        return listaPanel;
    }

    public void setListaPanel(JPanel listaPanel) {
        this.listaPanel = listaPanel;
    }

    public JScrollPane getTestsPanel() {
        return testsPanel;
    }

    public void setTestsPanel(JScrollPane testsPanel) {
        this.testsPanel = testsPanel;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
