/*
 * AddSPARQLJPanel.java
 *
 * Created on 19 de mayo de 2008, 19:12
 */

package code.google.com.p.ontologytesting.gui.tests;

import code.google.com.p.ontologytesting.gui.auxiliarpanels.FormatTestsJDialog;
import code.google.com.p.ontologytesting.gui.auxiliarclasess.AniadirPanelDeAviso;
import code.google.com.p.ontologytesting.gui.auxiliarclasess.ControladorTests;
import code.google.com.p.ontologytesting.gui.auxiliarclasess.OpcionesMenu;
import code.google.com.p.ontologytesting.gui.*;
import code.google.com.p.ontologytesting.gui.auxiliarclasess.ExecuteTest;
import code.google.com.p.ontologytesting.gui.auxiliarclasess.ProgressListener;
import code.google.com.p.ontologytesting.model.reasonerinterfaz.*;
import code.google.com.p.ontologytesting.model.*;
import code.google.com.p.ontologytesting.persistence.IOManagerImplementation;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import code.google.com.p.ontologytesting.gui.auxiliarpanels.ProgressControlJDialog;

/**
 *
 * @author  Saruskas
 */
public class AddSPARQLJPanel extends javax.swing.JPanel {

    private boolean testSinNombre,sinConsultas,
            ambosNecesarios,continuarSinInstancias,queryValida,resultValido,continuar,addInst;
    private ScenarioTest scenario,scenarioActual;
    private List<SparqlQueryOntology> listaDeConsultas;
    private int posListQuerysSel;
    private Reasoner jenaInterface;
    private InterfaceReasoner jena;
    private ValidarTests validarTest;
    private IOManagerImplementation persist = new IOManagerImplementation();
    private ControladorTests controlador;
    private OpcionesMenu menu;
    private AniadirPanelDeAviso panelAviso;
    private ProgressControlJDialog progres;
    
    public AddSPARQLJPanel(ScenarioTest s) {
        initComponents();
        panelAviso = new AniadirPanelDeAviso();
        controlador = ControladorTests.getInstance();
        listaDeConsultas = new ArrayList<SparqlQueryOntology>();
        sparqlTextArea.setLineWrap(true);
        sparqlTextArea.setWrapStyleWord(true);
        testDescTextArea.setLineWrap(true);
        testDescTextArea.setWrapStyleWord(true);
        resultTextArea.setLineWrap(true);
        resultTextArea.setWrapStyleWord(true);
        List<SparqlQueryOntology> lista = s.getSparqlQuerys();
        if(lista.size()>0){
            for(int i=0; i<lista.size();i++){
                listaDeConsultas.add(lista.get(i));
            }
            if(lista.size()>1){
                antQueryButton.setEnabled(false);
                sigQueryButton.setEnabled(true);
            }else{
                antQueryButton.setEnabled(false);
                sigQueryButton.setEnabled(false);
            }
            this.prepararNuevaConsultaCompleta(lista.get(0));
            this.setTestNameTextField(s.getNombre());
            this.setTestDescTextArea(s.getDescripcion());
        }
        this.inicializarVariables();
        menu = new OpcionesMenu();
        setScenario(s);
        setPosListQuerysSel(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nuevaConsultaButton = new javax.swing.JButton();
        limpiarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        testNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        testDescTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        sparqlTextArea = new javax.swing.JTextArea();
        sigQueryButton = new javax.swing.JButton();
        antQueryButton = new javax.swing.JButton();
        limpiarResultButton = new javax.swing.JButton();
        borrarConsultaJButton = new javax.swing.JButton();
        formatosPermitidos = new javax.swing.JButton();
        guardarEjecutarJButton = new javax.swing.JButton();
        ejecutarJButton = new javax.swing.JButton();
        guardarJButton = new javax.swing.JButton();
        addInstanciasButton = new javax.swing.JButton();

        jLabel1.setText("Introduzca la consulta en SPARQL:");

        nuevaConsultaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/add.png"))); // NOI18N
        nuevaConsultaButton.setToolTipText("Nueva consulta");
        nuevaConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaConsultaButtonActionPerformed(evt);
            }
        });

        limpiarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/paintbrush.png"))); // NOI18N
        limpiarButton.setToolTipText("Limpiar");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Introduzca el nombre del test:");

        testNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testNameTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Añada una descripción para el test:");

        testDescTextArea.setColumns(20);
        testDescTextArea.setRows(5);
        jScrollPane2.setViewportView(testDescTextArea);

        jLabel4.setText("Resultado esperado:");

        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        jScrollPane3.setViewportView(resultTextArea);

        sparqlTextArea.setColumns(20);
        sparqlTextArea.setRows(5);
        jScrollPane1.setViewportView(sparqlTextArea);

        sigQueryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/resultset_next.png"))); // NOI18N
        sigQueryButton.setToolTipText("Siguiente");
        sigQueryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigQueryButtonActionPerformed(evt);
            }
        });

        antQueryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/resultset_previous.png"))); // NOI18N
        antQueryButton.setToolTipText("Anterior");
        antQueryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antQueryButtonActionPerformed(evt);
            }
        });

        limpiarResultButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/paintbrush.png"))); // NOI18N
        limpiarResultButton.setToolTipText("Limpiar");
        limpiarResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarResultButtonActionPerformed(evt);
            }
        });

        borrarConsultaJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/cancel.png"))); // NOI18N
        borrarConsultaJButton.setToolTipText("Borrar");
        borrarConsultaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarConsultaJButtonActionPerformed(evt);
            }
        });

        formatosPermitidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/information.png"))); // NOI18N
        formatosPermitidos.setToolTipText("Formatos Permitidos");
        formatosPermitidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatosPermitidosActionPerformed(evt);
            }
        });

        guardarEjecutarJButton.setText("Guardar y Ejecutar");
        guardarEjecutarJButton.setToolTipText("Guardar y Ejecutar");
        guardarEjecutarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarEjecutarJButtonActionPerformed(evt);
            }
        });

        ejecutarJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/cog.png"))); // NOI18N
        ejecutarJButton.setToolTipText("Ejecutar");
        ejecutarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarJButtonActionPerformed(evt);
            }
        });

        guardarJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/disk.png"))); // NOI18N
        guardarJButton.setToolTipText("Guardar");
        guardarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarJButtonActionPerformed(evt);
            }
        });

        addInstanciasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/add.png"))); // NOI18N
        addInstanciasButton.setText("Instancias");
        addInstanciasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInstanciasButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 311, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .add(limpiarButton)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(borrarConsultaJButton)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(antQueryButton)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(sigQueryButton)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(nuevaConsultaButton)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 335, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(limpiarResultButton)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel4)
                                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(testNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 267, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 240, Short.MAX_VALUE)
                        .add(formatosPermitidos))
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 458, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(guardarJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ejecutarJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(guardarEjecutarJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addInstanciasButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(testNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(formatosPermitidos))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(guardarJButton)
                    .add(ejecutarJButton)
                    .add(guardarEjecutarJButton)
                    .add(addInstanciasButton))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 182, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(borrarConsultaJButton)
                                    .add(limpiarButton)))
                            .add(layout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(sigQueryButton)
                                    .add(antQueryButton)
                                    .add(nuevaConsultaButton)))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(limpiarResultButton)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void nuevaConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaConsultaButtonActionPerformed
// TODO add your handling code here:
    String q = this.getSPARQLQuery();
    String r = this.getResultTextArea();
    this.inicializarVariables();
    this.consultaVacia(q, r);
    if(sinConsultas==false){
        this.consultaCompleta(q, r);
        continuar = consultaOK(q, r);
        if(continuar==true){
            this.validarConsulta(q);
            if(continuar==true){
                this.validarResultado(r);
            }
        }
        if(continuar==true){
            SparqlQueryOntology query = new SparqlQueryOntology(q,r);
            if((this.getListaDeConsultas().size()==0) || (posListQuerysSel==listaDeConsultas.size())){
                listaDeConsultas.add(query);
                this.prepararNuevaConsultaVacia();
                antQueryButton.setEnabled(true);
                sigQueryButton.setEnabled(false);
                posListQuerysSel++;
            }else{
                this.reemplazarConsulta(query, posListQuerysSel);
                this.prepararNuevaConsultaVacia();
                sigQueryButton.setEnabled(false);
                posListQuerysSel = listaDeConsultas.size();
                antQueryButton.setEnabled(true);
            }
       }else if(resultValido==false){
            panelAviso.warningAction("El formato del resultado no es válido", MainApplicationJFrame.getInstance());
            continuar=false;
       }
    }else{
        JOptionPane.showMessageDialog(MainApplicationJFrame.getInstance(),"Actualmente tiene una consulta nueva para añadir",
        "Warning Message",JOptionPane.WARNING_MESSAGE);
    }
}//GEN-LAST:event_nuevaConsultaButtonActionPerformed


private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
// TODO add your handling code here:
    this.setSPARQLQuery("");
}//GEN-LAST:event_limpiarButtonActionPerformed

private void antQueryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antQueryButtonActionPerformed
// TODO add your handling code here:
    inicializarVariables();
    String q = this.getSPARQLQuery();
    String r = this.getResultTextArea();
    this.consultaVacia(q, r);
    if(sinConsultas==false){
        this.consultaCompleta(q, r);
        continuar = consultaOK(q, r);
        if(continuar==true){
            this.validarConsulta(q);
            if(continuar==true){
                this.validarResultado(r);
            }
        } 
    }   
    if(continuar==true){
        SparqlQueryOntology query = new SparqlQueryOntology(q,r);
        SparqlQueryOntology querySig = listaDeConsultas.get(posListQuerysSel-1);
        if(posListQuerysSel==listaDeConsultas.size()){
           listaDeConsultas.add(query); 
           this.prepararNuevaConsultaCompleta(querySig);
           sigQueryButton.setEnabled(true);
        }else{
            this.reemplazarConsulta(query, posListQuerysSel);
            this.prepararNuevaConsultaCompleta(querySig);
            sigQueryButton.setEnabled(true);
        }
        posListQuerysSel--; 
        if(posListQuerysSel==0){
            antQueryButton.setEnabled(false);
        }
    }   
}//GEN-LAST:event_antQueryButtonActionPerformed

private void sigQueryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigQueryButtonActionPerformed
// TODO add your handling code here:
    inicializarVariables();
    String q = this.getSPARQLQuery();
    String r = this.getResultTextArea();
    this.consultaVacia(q, r);
    if(sinConsultas==false){
        this.consultaCompleta(q, r);
        continuar = consultaOK(q, r);
        if(continuar==true){
            this.validarConsulta(q);
            if(continuar==true){
                this.validarResultado(r);
            }
        } 
    }
    if(continuar==true){ 
        SparqlQueryOntology query = new SparqlQueryOntology(q,r);
        this.reemplazarConsulta(query, posListQuerysSel);
        SparqlQueryOntology querySig = listaDeConsultas.get(posListQuerysSel+1);
        this.prepararNuevaConsultaCompleta(querySig);
        posListQuerysSel++; 
        if(posListQuerysSel==listaDeConsultas.size()-1){
            sigQueryButton.setEnabled(false);
        }
        if(posListQuerysSel<listaDeConsultas.size()){
            antQueryButton.setEnabled(true);
        }
    }   
}//GEN-LAST:event_sigQueryButtonActionPerformed

private void limpiarResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarResultButtonActionPerformed
// TODO add your handling code here:
    this.setResultTextArea("");
}//GEN-LAST:event_limpiarResultButtonActionPerformed

private void borrarConsultaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarConsultaJButtonActionPerformed
// TODO add your handling code here:
    inicializarVariables();
    if(listaDeConsultas.size()==0 || (this.getSPARQLQuery().equals("") && this.getResultTextArea().equals(""))){
        JOptionPane.showMessageDialog(MainApplicationJFrame.getInstance(),"No hay ninguna consulta que borrar",
        "Warning Message",JOptionPane.WARNING_MESSAGE);
    }else if(listaDeConsultas.size()==1){
        this.prepararNuevaConsultaVacia();
        setListaDeConsultas(new ArrayList<SparqlQueryOntology>());
        setPosListQuerysSel(0);
    }else{
        if(posListQuerysSel==listaDeConsultas.size()-1){
            SparqlQueryOntology querySig = listaDeConsultas.get(posListQuerysSel-1);
            listaDeConsultas.remove(posListQuerysSel);
            this.prepararNuevaConsultaCompleta(querySig);
            sigQueryButton.setEnabled(false);
            posListQuerysSel--;
        
        }else{
            SparqlQueryOntology querySig = listaDeConsultas.get(posListQuerysSel+1);
            this.prepararNuevaConsultaCompleta(querySig);
            listaDeConsultas.remove(posListQuerysSel);
        }
        if(posListQuerysSel==listaDeConsultas.size()-1){
            sigQueryButton.setEnabled(false);
        }
        if(listaDeConsultas.size()==1){
            sigQueryButton.setEnabled(false);
            antQueryButton.setEnabled(false);
        } 
    }
    
    
}//GEN-LAST:event_borrarConsultaJButtonActionPerformed

private void formatosPermitidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN FIRST:event_formatosPermitidosActionPerformed
// TODO add your handling code here:
    FormatTestsJDialog format = new FormatTestsJDialog(null,true,5);
    format.setLocationRelativeTo(MainApplicationJFrame.getInstance());
    format.setModal(false);
    format.setVisible(true);
}                                                  

private void testNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testNameTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_testNameTextFieldActionPerformed

private void addInstanciasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInstanciasButtonActionPerformed
// TODO add your handling code here:
    addInst=true;
    if(persist.testYaGuardado(getScenario())==false){
        guardarTest();
    }
    menu.editarInstancias(this.getScenario());
}//GEN-LAST:event_addInstanciasButtonActionPerformed

private void guardarJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
// TODO add your handling code here:
    guardarTest();
}                                              

public boolean guardarTest(){
    prepararGuardar();
    if(continuar==true){
        if(continuarSinInstancias==true){
            this.realizarAccion(true, false);
        }else{
            MainApplicationJFrame.getInstance().cargarInstancia(this.getScenario().getInstancias(),"Asociar Instancias a Test");
        }
    }
    return continuar;
}

private void guardarEjecutarJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                       
// TODO add your handling code here:
    prepararGuardar();
    if(continuar==true){
        if(continuarSinInstancias==true){
            this.realizarAccion(true, true);
        }else{
            MainApplicationJFrame.getInstance().cargarInstancia(this.getScenario().getInstancias(),"Asociar Instancias a Test");
        }
    }
}                                                      

private void ejecutarJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
// TODO add your handling code here:
    prepararGuardar();
    if(continuar==true){
        if(continuarSinInstancias==true){
            this.realizarAccion(false, true);
        }else{
            MainApplicationJFrame.getInstance().cargarInstancia(this.getScenario().getInstancias(),"Asociar Instancias a Test");
        }
    }
}                                               

public void realizarAccion(boolean guardar, boolean ejecutar){
    persist = new IOManagerImplementation();
    if(guardar==true){
        if(persist.testYaGuardado(getScenario())==true){
            persist.replaceScenarioLocally(getScenario());
        }else{
            persist.saveTestInMemory(getScenario());
            controlador.setTestInstSatGuardado(true);
        }
        this.setScenarioActual(new ScenarioTest(scenario));
    }
    if(ejecutar==true){
        try{
            ExecuteTest execTest = new ExecuteTest(getScenario());
            progres = new ProgressControlJDialog(execTest);
            JProgressBar progresBar = progres.getProgressBar();
            execTest.addPropertyChangeListener(new ProgressListener(progresBar,progres,true));
            progresBar.setIndeterminate(true);
            execTest.execute();
            progres.setVisible(true);
        }catch (ExceptionReadOntology ex){
            panelAviso.errorAction("No se pudo ejecutar el test. Ontología no válida", MainApplicationJFrame.getInstance());
        }
    }
    if(guardar==true && ejecutar==false){
        if(addInst==false){
            panelAviso.confirmAction("Test Guardado", MainApplicationJFrame.getInstance());
        }
    }
    menu.actualizarListaDeTestsSparql(CollectionTest.getInstance().getScenariotest());  
}

public void reemplazarConsulta(SparqlQueryOntology query,int pos){
    if(pos==listaDeConsultas.size()){
        listaDeConsultas.add(query);
    }else{
        listaDeConsultas.remove(pos);
        listaDeConsultas.add(pos, query);
    }
}

public void prepararNuevaConsultaVacia(){
    this.setSPARQLQuery("");
    this.setResultTextArea("");
}

public void prepararNuevaConsultaCompleta(SparqlQueryOntology query){
    this.setSPARQLQuery(query.getQuery());
    this.setResultTextArea(query.getResultexpected());
}

public void consultaVacia(String q, String r){
    if(q.equals("") && r.equals("")){
        sinConsultas=true;
    }
}

public void consultaCompleta(String query, String result){
    if((query.equals("") && !result.equals("")) || (!query.equals("") && result.equals(""))){
        ambosNecesarios=true;
    }
}

public boolean consultaOK(String query, String result){
    if(resultValido==true && ambosNecesarios==false && sinConsultas==false){
        continuar=true;
    }else if(sinConsultas==true){
        panelAviso.warningAction("Debe introducir alguna consulta", MainApplicationJFrame.getInstance());
        continuar=false;
    }else if(ambosNecesarios==true){
        panelAviso.warningAction("Ambos campos CONSULTA y RESULTADO ESPERADO son obligatorios", MainApplicationJFrame.getInstance());
        continuar=false;
    }else if(queryValida==false && resultValido==false){
        panelAviso.warningAction("La consulta introducida y el resultado no son válidos", MainApplicationJFrame.getInstance());
        continuar=false;
    }else if(queryValida==false){
        panelAviso.warningAction("La consulta introducida no es válida", MainApplicationJFrame.getInstance());
        continuar=false;
    }else if(resultValido==false){
        panelAviso.warningAction("El formato del resultado no es válido", MainApplicationJFrame.getInstance());
        continuar=false;
    }
    return continuar;
}

public void validarConsulta(String query){
    jenaInterface = new Reasoner();   
    jena = jenaInterface.getReasoner();
    if(jenaInterface.isCargado()==true){ 
        try{
            boolean res = jena.validarSparqlQuery(query); 
            if(res==false){
                panelAviso.warningAction("Sólo está permitidas las consultas SELECT", MainApplicationJFrame.getInstance());
                queryValida=false;
                continuar=false;
            }
        }catch(Exception ex){
            panelAviso.warningAction("La consulta SPARQL no es válida", MainApplicationJFrame.getInstance());
            queryValida=false;
            continuar=false;
        }
    }else{
        panelAviso.warningAction("Error en la aplicación", MainApplicationJFrame.getInstance());
        queryValida=false;
        continuar=false;
    }
}

public void validarResultado(String resul){
    validarTest = new ValidarTests();
    if(!validarTest.validarSparqlResult(resul)){
        resultValido=false;
        continuar=false;
    }
}

public void prepararGuardar(){
    inicializarVariables();
    String nombreTest = this.getTestNameTextField();
    String descTest = this.getTestDescTextArea();
    String query = this.getSPARQLQuery();
    String result = this.getResultTextArea();
    SparqlQueryOntology q = new SparqlQueryOntology(query,result);
    if(testVacio(nombreTest)==true){
        testSinNombre=true;
    }
    //if(!this.inListSparqlQuerys(q)){
        this.consultaCompleta(query, result);
        this.consultaVacia(query, result);
        continuar = this.consultaOK(query, result);
        if(continuar==true){
            this.validarConsulta(query);
            if(continuar==true){
                this.validarResultado(result);
                if(continuar==true){
                    this.reemplazarConsulta(q, posListQuerysSel);
                }else{
                    panelAviso.warningAction("El formato del resultado no es válido", MainApplicationJFrame.getInstance());
                    continuar=false;
                }
            }
        }
    //}
    if(continuar==true){
        if(testSinNombre==false && listaDeConsultas.size()>0 && continuar==true){  
            boolean res = this.preguntarSiContinuarSinInstancias();
            if(res==true){
                scenario.setDescripcion(descTest);
                scenario.setNombre(nombreTest);
                List<SparqlQueryOntology> querys = new ArrayList<SparqlQueryOntology>(this.getListaDeConsultas());
                scenario.setSparqlQuerys(querys); 
            }
        }else if(testSinNombre==true){
                panelAviso.warningAction("El nombre del test es obligatorio", MainApplicationJFrame.getInstance());
                continuar=false;
        }else if(listaDeConsultas.size()==0 && testSinNombre==false){
            panelAviso.warningAction("Al menos debe introducir una consulta para ejecutar el test", MainApplicationJFrame.getInstance());
            continuar=false;
        }
    }
}

public boolean preguntarSiContinuarSinInstancias(){
    if(addInst==false){
        if(scenario.tieneInstanciasAsociadas()==false){
            int n = JOptionPane.showConfirmDialog(MainApplicationJFrame.getInstance(), "El test no tiene instancias asociadas. " +
                    "¿Desea continuar?", "Warning Message",JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.NO_OPTION){
                continuarSinInstancias=false;
            }else if(n == JOptionPane.YES_OPTION){
                continuarSinInstancias=true;
            }
        }
    }else continuarSinInstancias=true;
    return continuarSinInstancias;
}

public boolean testVacio(String nombre){
    if(nombre.equals("")){
        return true;
    }else{
        return false;
    }
}

public void inicializarVariables(){
    continuarSinInstancias=true;
    resultValido=true;
    queryValida=true;
    testSinNombre=false;
    sinConsultas=false;
    continuar=true;
    ambosNecesarios=false;
}      
    
    public List<SparqlQueryOntology> getListaDeConsultas() {
        return listaDeConsultas;
    }

    public void setListaDeConsultas(List<SparqlQueryOntology> aListaDeConsultas) {
        listaDeConsultas = aListaDeConsultas;
    }

    public String getResultTextArea() {
        return resultTextArea.getText();
    }

    public void setResultTextArea(String aResultTextArea) {
        resultTextArea.setText(aResultTextArea);
    }

    public String getSPARQLQuery() {
        return getSparqlTextArea().getText();
    }

    public void setSPARQLQuery(String aSparqlTextArea) {
        getSparqlTextArea().setText(aSparqlTextArea);
    }

    public String getTestDescTextArea() {
        return testDescTextArea.getText();
    }

    public void setTestDescTextArea(String aTestDescTextArea) {
        testDescTextArea.setText(aTestDescTextArea);
    }

    public String getTestNameTextField() {
        return testNameTextField.getText();
    }

    public void setTestNameTextField(String aTestNameTextField) {
        testNameTextField.setText(aTestNameTextField);
    }

    public javax.swing.JTextArea getSparqlTextArea() {
        return sparqlTextArea;
    }

    public void setAntQueryButton(boolean state) {
        antQueryButton.setEnabled(state);
    }

    public void setSigQueryButton(boolean state) {
        sigQueryButton.setEnabled(state);
    }

    public int getPosListQuerysSel() {
            return posListQuerysSel;
    }

    public void setPosListQuerysSel(int aPosListQuerysSel) {
        posListQuerysSel = aPosListQuerysSel;
    }

    public ScenarioTest getScenario() {
            return scenario;
        }

    public void setScenario(ScenarioTest scenario) {
        this.scenario = scenario;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInstanciasButton;
    private javax.swing.JButton antQueryButton;
    private javax.swing.JButton borrarConsultaJButton;
    private javax.swing.JButton ejecutarJButton;
    private javax.swing.JButton formatosPermitidos;
    private javax.swing.JButton guardarEjecutarJButton;
    private javax.swing.JButton guardarJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JButton limpiarResultButton;
    private javax.swing.JButton nuevaConsultaButton;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JButton sigQueryButton;
    private javax.swing.JTextArea sparqlTextArea;
    private javax.swing.JTextArea testDescTextArea;
    private javax.swing.JTextField testNameTextField;
    // End of variables declaration//GEN-END:variables

    public ScenarioTest getScenarioActual() {
        return scenarioActual;
    }

    public void setScenarioActual(ScenarioTest scenarioActual) {
        this.scenarioActual = scenarioActual;
    }


}
