/*
 * addInstancesTFJPanel.java
 *
 * Created on 24 de abril de 2008, 10:46
 */

package ontologytestinggui;

import javax.swing.JFrame;

/**
 *
 * @author  sara_garcia
 */
public class addInstancesTFJPanel extends javax.swing.JPanel {    
    
    public saveCommentJDialog addcomment= new saveCommentJDialog(new JFrame(),true);
    
    /** Creates new form addInstancesTFJPanel */
    public addInstancesTFJPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queryTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        selectCheckBox = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        comentButton = new javax.swing.JButton();

        queryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryTextFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Duplicar");

        jRadioButton1.setText("True");

        jRadioButton2.setText("False");

        comentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesgui/comment.png"))); // NOI18N
        comentButton.setText("Comentario");
        comentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(queryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(comentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(64, 64, 64)
                .addComponent(selectCheckBox)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(queryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)
                        .addComponent(comentButton))
                    .addComponent(selectCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void queryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryTextFieldActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_queryTextFieldActionPerformed

private void comentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comentButtonActionPerformed
// TODO add your handling code here:
    addcomment.setTitle("Comentar query");
    addcomment.setVisible(true);
}//GEN-LAST:event_comentButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comentButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField queryTextField;
    private javax.swing.JCheckBox selectCheckBox;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JRadioButton getJRadioButton1() {
        return jRadioButton1;
    }

    public void setJRadioButton1(javax.swing.JRadioButton jRadioButton1) {
        this.jRadioButton1 = jRadioButton1;
    }

    public javax.swing.JRadioButton getJRadioButton2() {
        return jRadioButton2;
    }

    public void setJRadioButton2(javax.swing.JRadioButton jRadioButton2) {
        this.jRadioButton2 = jRadioButton2;
    }

    public javax.swing.JTextField getQueryTextField() {
        return queryTextField;
    }

    public void setQueryTextField(javax.swing.JTextField queryTextField) {
        this.queryTextField = queryTextField;
    }

    public javax.swing.JCheckBox getSelectCheckBox() {
        return selectCheckBox;
    }

    public void setSelectCheckBox(javax.swing.JCheckBox selectCheckBox) {
        this.selectCheckBox = selectCheckBox;
    }

}
