/*
 * ConfigurationJPanel.java
 *
 * Created on 29 de julio de 2008, 8:27
 */

package code.google.com.p.ontologytesting.gui;

import java.awt.Component;
import java.io.File;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author  sara.garcia
 */
public class ConfigurationJPanel extends javax.swing.JPanel {

    public static boolean isHaSidoConfigurado() {
        return haSidoConfigurado;
    }

    public static void setHaSidoConfigurado(boolean aHaSidoConfigurado) {
        haSidoConfigurado = aHaSidoConfigurado;
    }

    private String inicio="";
    private JFileChooser filechooser;
    private Component frame;
    private static boolean haSidoConfigurado=true;
    
    /** Creates new form ConfigurationJPanel */
    public ConfigurationJPanel() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(siRadioButton);
        group.add(noRadioButton);
        group.add(restaurarRadioButton);
        descripcionEditorPane.setContentType("text/html");
        inicio="<html>En esta pantalla usted podra especificar la ubicacion de " +
                "sus tests en su ordenador. <br><br>" +
                "Por defecto estos se guardaran dentro de la carpeta del proyecto" +
                " en las siguientes subcarpetas: <br>" +
                "Tests Simples: ./Simple Tests/ <br>" +
                "Tests SPARQL: ./Sparql Tests <br>" +
                "Conjunto de instancias: ./Instancias <br><br>" +
                "Si usted desea modificar esta configuarción, por favor, seleccione " +
                "el campo 'Si' y complete los campos que se le indican. Si por el " +
                "contrario desea mantener la configuarcion por defecto, seleccione " +
                "'No'.<br>" +
                "Si en algun momento quiere recuperar la configuracion por defecto " +
                "seleccione el campo 'Restaurar valores predeterminados'<br></html>";
        descripcionEditorPane.setEditable(false);
        descripcionEditorPane.setText(inicio);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionEditorPane = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        testsSimplesTextField = new javax.swing.JTextField();
        testsSparqlTextField = new javax.swing.JTextField();
        instanciasTextField = new javax.swing.JTextField();
        examinarTestsSimplesButton = new javax.swing.JButton();
        examinarTestsSparqlButton = new javax.swing.JButton();
        examinarInstanciasButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        restaurarRadioButton = new javax.swing.JRadioButton();
        siRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        setEnabled(false);

        jScrollPane1.setViewportView(descripcionEditorPane);

        jLabel1.setText("¿Desea modificar la configuracion actual?");

        jLabel2.setText("Seleccione la ubicacion para el conjunto de Tests Simples:");
        jLabel2.setEnabled(false);

        jLabel3.setText("Seleccione la ubicacion para el conjunto de Tests SPARQL:");
        jLabel3.setEnabled(false);

        jLabel4.setText("Seleccione la ubicacion para el conjunto de Instancias:");
        jLabel4.setEnabled(false);

        testsSimplesTextField.setEnabled(false);

        testsSparqlTextField.setEnabled(false);

        instanciasTextField.setEnabled(false);

        examinarTestsSimplesButton.setText("Examinar");
        examinarTestsSimplesButton.setEnabled(false);
        examinarTestsSimplesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examinarTestsSimplesButtonActionPerformed(evt);
            }
        });

        examinarTestsSparqlButton.setText("Examinar");
        examinarTestsSparqlButton.setEnabled(false);
        examinarTestsSparqlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examinarTestsSparqlButtonActionPerformed(evt);
            }
        });

        examinarInstanciasButton.setText("Examinar");
        examinarInstanciasButton.setEnabled(false);
        examinarInstanciasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examinarInstanciasButtonActionPerformed(evt);
            }
        });

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Restaurar valores predeterminados:");

        restaurarRadioButton.setText("Restaurar");

        siRadioButton.setText("Si");
        siRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siRadioButtonActionPerformed(evt);
            }
        });

        noRadioButton.setText("No");
        noRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRadioButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("CONFIGUARCION DEL SISTEMA PARA LA UBICACIÓN DE SUS TESTS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelarButton)
                .addGap(18, 18, 18)
                .addComponent(aceptarButton)
                .addGap(548, 548, 548))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addGap(288, 288, 288))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(siRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noRadioButton))
                    .addComponent(testsSimplesTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(testsSparqlTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instanciasTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(restaurarRadioButton))
                            .addComponent(examinarTestsSimplesButton)
                            .addComponent(examinarTestsSparqlButton)
                            .addComponent(examinarInstanciasButton))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siRadioButton)
                    .addComponent(noRadioButton)
                    .addComponent(restaurarRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testsSimplesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(examinarTestsSimplesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testsSparqlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(examinarTestsSparqlButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelarButton)
                            .addComponent(aceptarButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(instanciasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(examinarInstanciasButton))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {instanciasTextField, testsSimplesTextField, testsSparqlTextField});

    }// </editor-fold>//GEN-END:initComponents

private void siRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siRadioButtonActionPerformed
// TODO add your handling code here:
    examinarInstanciasButton.setEnabled(true);
    examinarTestsSimplesButton.setEnabled(true);
    examinarTestsSparqlButton.setEnabled(true);
    instanciasTextField.setEnabled(true);
    testsSimplesTextField.setEnabled(true);
    testsSparqlTextField.setEnabled(true);
    jLabel2.setEnabled(true);
    jLabel3.setEnabled(true);
    jLabel4.setEnabled(true);
}//GEN-LAST:event_siRadioButtonActionPerformed

private void noRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRadioButtonActionPerformed
// TODO add your handling code here:
    examinarInstanciasButton.setEnabled(false);
    examinarTestsSimplesButton.setEnabled(false);
    examinarTestsSparqlButton.setEnabled(false);
    instanciasTextField.setEnabled(false);
    testsSimplesTextField.setEnabled(false);
    testsSparqlTextField.setEnabled(false);
    jLabel2.setEnabled(false);
    jLabel3.setEnabled(false);
    jLabel4.setEnabled(false);
}//GEN-LAST:event_noRadioButtonActionPerformed

private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
 // TODO add your handling code here:
    if(siRadioButton.isSelected()){
       if(!this.getInstanciasTextField().equals("") && !this.getTestsSimplesTextField().equals("") 
               && !this.getTestsSparqlTextField().equals("")){
           //Si es valida la ruta
           Configuration.setPathTestSimples(this.getTestsSimplesTextField());  
           Configuration.setPathTestSparql(this.getTestsSparqlTextField());
           Configuration.setPathInstancias(this.getInstanciasTextField());
           JOptionPane.showMessageDialog(frame,"Su configuración ha sido " +
                   "guardada correctamente.","Confirm Message",JOptionPane.INFORMATION_MESSAGE);
           ConfigurationJPanel.setHaSidoConfigurado(true);
           ContentMainJFrame.getContentPanel().remove(this);
           ContentMainJFrame.getContentPanel().add(ContentMainJFrame.getMainPanel());
           ContentMainJFrame.setActual(0);
           ContentMainJFrame.getContentPanel().getParent().validate();
       }else{
            JOptionPane.showMessageDialog(frame,"Debe completar los tres campos" +
                    "para coninuar","Warning Message",JOptionPane.WARNING_MESSAGE);
       }
    }else if(noRadioButton.isSelected()){
        Configuration.setPathTestSimples("./Simple Tests");  
        Configuration.setPathTestSparql("./Sparql Tests");
        Configuration.setPathInstancias("./Instancias");
        JOptionPane.showMessageDialog(frame,"Se mantiene la configuracion establecida" +
                "por defecto.","Confirm Message",JOptionPane.INFORMATION_MESSAGE);
        ConfigurationJPanel.setHaSidoConfigurado(true);
        ContentMainJFrame.getContentPanel().remove(this);
        ContentMainJFrame.getContentPanel().add(ContentMainJFrame.getMainPanel());
        ContentMainJFrame.setActual(0);
        ContentMainJFrame.getContentPanel().getParent().validate();
    }else if(restaurarRadioButton.isSelected()){
        Configuration.setPathTestSimples("./Simple Tests");  
        Configuration.setPathTestSparql("./Sparql Tests");
        Configuration.setPathInstancias("./Instancias");
        JOptionPane.showMessageDialog(frame,"Se ha restaurado la configuracion" +
                "original.","Confirm Message",JOptionPane.INFORMATION_MESSAGE);
        ConfigurationJPanel.setHaSidoConfigurado(true);
        ContentMainJFrame.getContentPanel().remove(this);
        ContentMainJFrame.getContentPanel().add(ContentMainJFrame.getMainPanel());
        ContentMainJFrame.setActual(0);
        ContentMainJFrame.getContentPanel().getParent().validate();
    }else{
       JOptionPane.showMessageDialog(frame,"Debe seleccionar una opcion para " +
               "continuar.","Warning Message",JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_aceptarButtonActionPerformed

private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_cancelarButtonActionPerformed

private void examinarTestsSimplesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examinarTestsSimplesButtonActionPerformed
// TODO add your handling code here:
    filechooser = new JFileChooser();
    filechooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
    int option = filechooser.showOpenDialog(frame);
      if (option == JFileChooser.APPROVE_OPTION) {
          File selectedFile = filechooser.getSelectedFile();
            testsSimplesTextField.setText(selectedFile.getPath());   
      }
}//GEN-LAST:event_examinarTestsSimplesButtonActionPerformed

private void examinarTestsSparqlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examinarTestsSparqlButtonActionPerformed
// TODO add your handling code here:
    filechooser = new JFileChooser();
    filechooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
    int option = filechooser.showOpenDialog(frame);
      if (option == JFileChooser.APPROVE_OPTION) {
          File selectedFile = filechooser.getSelectedFile();
            testsSparqlTextField.setText(selectedFile.getPath());
      }
}//GEN-LAST:event_examinarTestsSparqlButtonActionPerformed

private void examinarInstanciasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examinarInstanciasButtonActionPerformed
// TODO add your handling code here:
    filechooser = new JFileChooser();
    filechooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
    int option = filechooser.showOpenDialog(frame);
      if (option == JFileChooser.APPROVE_OPTION) {
          File selectedFile = filechooser.getSelectedFile();
            instanciasTextField.setText(selectedFile.getPath());
      }
}//GEN-LAST:event_examinarInstanciasButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JEditorPane descripcionEditorPane;
    private javax.swing.JButton examinarInstanciasButton;
    private javax.swing.JButton examinarTestsSimplesButton;
    private javax.swing.JButton examinarTestsSparqlButton;
    private javax.swing.JTextField instanciasTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JRadioButton restaurarRadioButton;
    private javax.swing.JRadioButton siRadioButton;
    private javax.swing.JTextField testsSimplesTextField;
    private javax.swing.JTextField testsSparqlTextField;
    // End of variables declaration//GEN-END:variables

    public String getInstanciasTextField() {
        return instanciasTextField.getText();
    }

    public void setInstanciasTextField(String ainstanciasTextField) {
        instanciasTextField.setText(ainstanciasTextField);
    }

    public String getTestsSimplesTextField() {
        return testsSimplesTextField.getText();
    }

    public void setTestsSimplesTextField(String atestsSimplesTextField) {
        testsSimplesTextField.setText(atestsSimplesTextField);
    }

    public String getTestsSparqlTextField() {
        return testsSparqlTextField.getText();
    }

    public void setTestsSparqlTextField(String atestsSparqlTextField) {
        testsSparqlTextField.setText(atestsSparqlTextField);
    }

}
