/*
 * TextInstancesTextAreaJPanel.java
 *
 * Created on 30 de julio de 2008, 18:03
 */

package code.google.com.p.ontologytesting.gui;

import code.google.com.p.ontologytesting.model.Auxiliar;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.WindowConstants;

/**
 *
 * @author  saruskas
 */
public class TestInstancesTextAreaJPanel extends javax.swing.JPanel {

    private AddComentJDialog frameComent;
    private Frame frame;
    private int posicion;
    
    /** Creates new form TextInstancesTextAreaJPanel */
    public TestInstancesTextAreaJPanel(int type) {
        initComponents();
        if(type==0){
            int pos = Auxiliar.getContadorRet();
            this.setPosicion(pos);
            int cont = pos+1;
            Auxiliar.setContadorRet(cont);
        }else if(type==1){
            int pos = Auxiliar.getContadorClasi();
            this.setPosicion(pos);
            int cont = pos+1;
            Auxiliar.setContadorClasi(cont);
        }
        frameComent = new AddComentJDialog(frame,true); 
        frameComent.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }

    public TestInstancesTextAreaJPanel(int type,String query, String result, String coment) {
        initComponents();
        queryTextField.setText(query);
        resultTextArea.setText(result);
        frameComent = new AddComentJDialog(frame,true); 
        frameComent.setComent(coment);
        frameComent.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queryTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        comentarioButton = new javax.swing.JButton();
        borrarButton = new javax.swing.JButton();
        duplicarButton = new javax.swing.JButton();

        queryTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                queryTextFieldMouseClicked(evt);
            }
        });

        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        resultTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultTextAreaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resultTextArea);

        comentarioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/comment_add.png"))); // NOI18N
        comentarioButton.setText("Comentario");
        comentarioButton.setToolTipText("Añadir comentario");
        comentarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comentarioButtonActionPerformed(evt);
            }
        });

        borrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/delete.png"))); // NOI18N
        borrarButton.setText("Borrar");
        borrarButton.setToolTipText("Borrar");
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });

        duplicarButton.setText("Duplicar");
        duplicarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duplicarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(queryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comentarioButton)
                .addGap(30, 30, 30)
                .addComponent(borrarButton)
                .addGap(32, 32, 32)
                .addComponent(duplicarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comentarioButton)
                        .addComponent(borrarButton)
                        .addComponent(duplicarButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(queryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void comentarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comentarioButtonActionPerformed
// TODO add your handling code here:
    System.out.println("Pos "+this.getPosicion());
    frameComent.setVisible(true);
}//GEN-LAST:event_comentarioButtonActionPerformed

private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
// TODO add your handling code here:
   this.setVisible(false);
   int tab = GroupTestsJPanel.getSelectedTabed();
   if(tab == 1){
       int finalPos=0;
       int p = this.getPosicion();
       int total = GroupTestsJPanel.getRetAyudaPanel().getComponentCount();
       for(int i=p+1;i<total;i++){
            TestInstancesTextAreaJPanel panel = (TestInstancesTextAreaJPanel) GroupTestsJPanel.getRetAyudaPanel().getComponent(i);
            int pos = panel.getPosicion();
            panel.setPosicion(pos-1);
            finalPos=pos-1;
       }
       GroupTestsJPanel.getRetAyudaPanel().remove(this);
       TestInstancesTextAreaJPanel pa = new TestInstancesTextAreaJPanel(0);
       pa.setPosicion(finalPos+1);
       GroupTestsJPanel.getRetAyudaPanel().add(pa);
   }else if(tab == 4){
       int finalPos=0;
       int p = this.getPosicion();
       int total = GroupTestsJPanel.getClasAyudaPanel().getComponentCount();
       for(int i=p+1;i<total;i++){
            TestInstancesTextAreaJPanel panel = (TestInstancesTextAreaJPanel) GroupTestsJPanel.getClasAyudaPanel().getComponent(i);
            int pos = panel.getPosicion();
            panel.setPosicion(pos-1);
            finalPos=pos-1;
       }
       GroupTestsJPanel.getClasAyudaPanel().remove(this);
       TestInstancesTextAreaJPanel pa = new TestInstancesTextAreaJPanel(1);
       pa.setPosicion(finalPos+1);
       GroupTestsJPanel.getClasAyudaPanel().add(pa);
   }  
}//GEN-LAST:event_borrarButtonActionPerformed

private void duplicarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplicarButtonActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_duplicarButtonActionPerformed

private void queryTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queryTextFieldMouseClicked
// TODO add your handling code here:
    getQueryTextField().setForeground(Color.BLACK);
}//GEN-LAST:event_queryTextFieldMouseClicked

private void resultTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultTextAreaMouseClicked
// TODO add your handling code here:
    getResultTextArea().setForeground(Color.BLACK);
}//GEN-LAST:event_resultTextAreaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarButton;
    private javax.swing.JButton comentarioButton;
    private javax.swing.JButton duplicarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField queryTextField;
    private javax.swing.JTextArea resultTextArea;
    // End of variables declaration//GEN-END:variables

    
    public AddComentJDialog getComment() {
        return frameComent;
    }

    public void setComment(AddComentJDialog comment) {
        this.frameComent = comment;
    }
    
    public void setQuery(String query){
        getQueryTextField().setText(query);
    }
    
    public String getQuery(){
        return getQueryTextField().getText();
    }

    public void setQueryResult(String result){
        getResultTextArea().setText(result);
    }
    
    public String getQueryResult(){
        return getResultTextArea().getText();
    }

    public javax.swing.JTextField getQueryTextField() {
        return queryTextField;
    }

    public javax.swing.JTextArea getResultTextArea() {
        return resultTextArea;
    }

    public int getPosicion() {
        return posicion;
    }

    public void setPosicion(int posicion) {
        this.posicion = posicion;
    }
}

