/*
 * AddSPARQLJPanel.java
 *
 * Created on 19 de mayo de 2008, 19:12
 */

package code.google.com.p.ontologytesting.guiNew;

import code.google.com.p.ontologytesting.model.jenainterfaz.*;
import code.google.com.p.ontologytesting.model.*;
import code.google.com.p.ontologytesting.persistence.SaveTest;
import code.google.com.p.ontologytesting.model.ValidarTests;
import java.awt.Component;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import javax.swing.JFrame;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author  Saruskas
 */
public class AddSPARQLJPanel extends javax.swing.JPanel {

    private boolean testSinNombre,testYaExiste,sinConsultas,
            ambosNecesarios,continuarSinInstancias,queryValida,resultValido,continuar;
    private JPanel panelTree;
    static final int desktopWidth = 700;
    static final int desktopHeight = 600;
    static JFrame frame;
    public static boolean seleccionado;
    public static ScenarioTest scenarioTestQuery;
    private int index=0;
    private boolean isAntSelected=false, isSigSelected=false;
    private Component comp;
    private ScenarioTest scenario,scenarioAEditar;
    private List<SparqlQueryOntology> listaDeConsultas;
    private int posListQuerysSel;
    private JenaInterface jenaInterface;
    private Jena jena;
    private boolean importado;
    private ValidarTests validarTest;
    private SaveTest saveTest;
    private AddInstancesClasPropJDialog addInst;
    private OntologyTestCase testcase;
    private ResultTests resultTests;
    private OntologyTestResult testresult;
    private boolean soloEjectuar;
    private ControladorTests controlador;
    private Utils utils;
    
    /** Creates new form AddSPARQLJPanel */
    /*public AddSPARQLJPanel(int tipo) {
        initComponents();
        
        sparqlTextArea.setLineWrap(true);
        sparqlTextArea.setWrapStyleWord(true);
        testDescTextArea.setLineWrap(true);
        testDescTextArea.setWrapStyleWord(true);
        resultTextArea.setLineWrap(true);
        resultTextArea.setWrapStyleWord(true);
        
        antQueryButton.setEnabled(false);
        sigQueryButton.setEnabled(false);
        
        this.inicializarVariables();
        setTipo(tipo);
        setScenarioAEditar(null);
        setScenario(new ScenarioTest()); 
        setImportado(false);
        listaDeConsultas = new ArrayList<SparqlQueryOntology>();
        setPosListQuerysSel(0);
        setSoloEjectuar(false);
    }*/
    
    public AddSPARQLJPanel(ScenarioTest s) {
        initComponents();
        controlador = ControladorTests.getInstance();
        listaDeConsultas = new ArrayList<SparqlQueryOntology>();
        sparqlTextArea.setLineWrap(true);
        sparqlTextArea.setWrapStyleWord(true);
        testDescTextArea.setLineWrap(true);
        testDescTextArea.setWrapStyleWord(true);
        resultTextArea.setLineWrap(true);
        resultTextArea.setWrapStyleWord(true);
        frame = new JFrame();
        setImportado(true);
        List<SparqlQueryOntology> lista = s.getSparqlQuerys();
        if(lista.size()>0){
            for(int i=0; i<lista.size();i++){
                listaDeConsultas.add(lista.get(i));
            }
            if(lista.size()>1){
                antQueryButton.setEnabled(false);
                sigQueryButton.setEnabled(true);
            }else{
                antQueryButton.setEnabled(false);
                sigQueryButton.setEnabled(false);
            }
            this.prepararNuevaConsultaCompleta(lista.get(0));
            this.setTestNameTextField(s.getNombre());
            this.setTestDescTextArea(s.getDescripcion());
        }
        this.inicializarVariables();
         utils = new Utils();
        scenarioAEditar = new ScenarioTest(s);
        setScenario(s);
        setSoloEjectuar(false);
        setPosListQuerysSel(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nuevaConsultaButton = new javax.swing.JButton();
        limpiarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        testNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        testDescTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        sparqlTextArea = new javax.swing.JTextArea();
        sigQueryButton = new javax.swing.JButton();
        antQueryButton = new javax.swing.JButton();
        limpiarResultButton = new javax.swing.JButton();
        borrarConsultaJButton = new javax.swing.JButton();
        formatosPermitidos = new javax.swing.JButton();
        guardarEjecutarJButton = new javax.swing.JButton();
        ejecutarJButton = new javax.swing.JButton();
        guardarJButton = new javax.swing.JButton();

        jLabel1.setText("Introduzca la consulta en SPARQL:");

        nuevaConsultaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/add.png"))); // NOI18N
        nuevaConsultaButton.setText("Añadir");
        nuevaConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaConsultaButtonActionPerformed(evt);
            }
        });

        limpiarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/paintbrush.png"))); // NOI18N
        limpiarButton.setText("Limpiar");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Introduzca el nombre del test:");

        jLabel3.setText("Añada una descripción para el test:");

        testDescTextArea.setColumns(20);
        testDescTextArea.setRows(5);
        jScrollPane2.setViewportView(testDescTextArea);

        jLabel4.setText("Resultado esperado:");

        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        jScrollPane3.setViewportView(resultTextArea);

        sparqlTextArea.setColumns(20);
        sparqlTextArea.setRows(5);
        jScrollPane1.setViewportView(sparqlTextArea);

        sigQueryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/resultset_next.png"))); // NOI18N
        sigQueryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigQueryButtonActionPerformed(evt);
            }
        });

        antQueryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/resultset_previous.png"))); // NOI18N
        antQueryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antQueryButtonActionPerformed(evt);
            }
        });

        limpiarResultButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/paintbrush.png"))); // NOI18N
        limpiarResultButton.setText("Limpiar");
        limpiarResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarResultButtonActionPerformed(evt);
            }
        });

        borrarConsultaJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/delete.png"))); // NOI18N
        borrarConsultaJButton.setText("Borrar");
        borrarConsultaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarConsultaJButtonActionPerformed(evt);
            }
        });

        formatosPermitidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/information.png"))); // NOI18N
        formatosPermitidos.setText("Formatos Permitidos");
        formatosPermitidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatosPermitidosActionPerformed(evt);
            }
        });

        guardarEjecutarJButton.setText("Guardar y Ejecutar");
        guardarEjecutarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarEjecutarJButtonActionPerformed(evt);
            }
        });

        ejecutarJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/cog.png"))); // NOI18N
        ejecutarJButton.setText("Ejecutar");
        ejecutarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarJButtonActionPerformed(evt);
            }
        });

        guardarJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code/google/com/p/ontologytesting/images/disk.png"))); // NOI18N
        guardarJButton.setText("Guardar");
        guardarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 311, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(160, 160, 160))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(limpiarButton)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(borrarConsultaJButton)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 96, Short.MAX_VALUE)
                                        .add(antQueryButton)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(sigQueryButton)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(nuevaConsultaButton))
                                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(layout.createSequentialGroup()
                                                .add(jLabel4)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 134, Short.MAX_VALUE))
                                            .add(layout.createSequentialGroup()
                                                .add(guardarJButton)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(ejecutarJButton)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)))
                                        .add(guardarEjecutarJButton))
                                    .add(limpiarResultButton)))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(testNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 267, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 418, Short.MAX_VALUE)
                                .add(formatosPermitidos)))
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(593, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                        .add(380, 380, 380))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(testNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(11, 11, 11)
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(23, 23, 23)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(jLabel4)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(formatosPermitidos)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(antQueryButton)
                    .add(sigQueryButton)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(limpiarButton)
                        .add(borrarConsultaJButton))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(limpiarResultButton)
                            .add(nuevaConsultaButton))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 75, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(guardarEjecutarJButton)
                            .add(ejecutarJButton)
                            .add(guardarJButton))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void nuevaConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaConsultaButtonActionPerformed
// TODO add your handling code here:
    String q = this.getSPARQLQuery();
    String r = this.getResultTextArea();
    this.inicializarVariables();
    
    this.consultaVacia(q, r);
    if(sinConsultas==false){
        this.consultaCompleta(q, r);

        continuar = consultaOK(q, r);

        if(continuar==true){
            this.validarConsulta(q);
            if(continuar==true){
                this.validarResultado(r);
            }
        }

        if(continuar==true){
            SparqlQueryOntology query = new SparqlQueryOntology(q,r);
            if((this.getListaDeConsultas().size()==0) || (posListQuerysSel==listaDeConsultas.size())){
                listaDeConsultas.add(query);
                this.prepararNuevaConsultaVacia();
                antQueryButton.setEnabled(true);
                sigQueryButton.setEnabled(false);
                posListQuerysSel++;
            }else{
                this.reemplazarConsulta(query, posListQuerysSel);
                this.prepararNuevaConsultaVacia();
                sigQueryButton.setEnabled(false);
                posListQuerysSel = listaDeConsultas.size();
                antQueryButton.setEnabled(true);
            }
       }else if(resultValido==false){
            JOptionPane.showMessageDialog(this,"El formato del resultado no es valido",
            "Warning Message",JOptionPane.WARNING_MESSAGE);
            continuar=false;
       }
    }else{
        JOptionPane.showMessageDialog(this,"Actualmente tiene una consulta nueva para añadir",
        "Warning Message",JOptionPane.WARNING_MESSAGE);
    }
}//GEN-LAST:event_nuevaConsultaButtonActionPerformed

public void reemplazarConsulta(SparqlQueryOntology query,int pos){
    if(pos==listaDeConsultas.size()){
        listaDeConsultas.add(query);
    }else{
        listaDeConsultas.remove(pos);
        listaDeConsultas.add(pos, query);
    }
}

public void prepararNuevaConsultaVacia(){
    this.setSPARQLQuery("");
    this.setResultTextArea("");
}

public void prepararNuevaConsultaCompleta(SparqlQueryOntology query){
    this.setSPARQLQuery(query.getQuerySparql());
    this.setResultTextArea(query.getResultexpected());
}

public void consultaVacia(String q, String r){
    if(q.equals("") && r.equals("")){
        sinConsultas=true;
    }
}

public void consultaCompleta(String query, String result){
    if((query.equals("") && !result.equals("")) || (!query.equals("") && result.equals(""))){
        ambosNecesarios=true;
    }
}

public boolean consultaOK(String query, String result){
    if(resultValido==true && ambosNecesarios==false && sinConsultas==false){
        continuar=true;
    }else if(sinConsultas==true){
        JOptionPane.showMessageDialog(this,"Debe introducir alguna consulta",
        "Warning Message",JOptionPane.WARNING_MESSAGE);
        continuar=false;
    }else if(ambosNecesarios==true){
        JOptionPane.showMessageDialog(this,"Ambos campos CONSULTA y RESULTADO ESPERADO son obligatorios",
        "Warning Message",JOptionPane.WARNING_MESSAGE);
        continuar=false;
    }else if(queryValida==false && resultValido==false){
        JOptionPane.showMessageDialog(this,"La consulta introducida y el resultado no son validos",
        "Warning Message",JOptionPane.WARNING_MESSAGE);
        continuar=false;
    }else if(queryValida==false){
        JOptionPane.showMessageDialog(this,"La consulta introducida no es valida",
        "Warning Message",JOptionPane.WARNING_MESSAGE);
        continuar=false;
    }else if(resultValido==false){
        JOptionPane.showMessageDialog(this,"El formato del resultado no es valido",
        "Warning Message",JOptionPane.WARNING_MESSAGE);
        continuar=false;
    }
    return continuar;
}

public void validarConsulta(String query){
    jenaInterface = new JenaInterface();   
    jena = jenaInterface.getJena();
    try{
        jena.validarSparqlQuery(query); 
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this,"La consulta SPARQL no es valida",
        "Warning Message",JOptionPane.WARNING_MESSAGE);
        queryValida=false;
        continuar=false;
    }
}

public void validarResultado(String resul){
    validarTest = new ValidarTests();
    if(!validarTest.validarSparqlResult(resul)){
        resultValido=false;
        continuar=false;
    }
}

private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
// TODO add your handling code here:
    this.setSPARQLQuery("");
}//GEN-LAST:event_limpiarButtonActionPerformed

private void antQueryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antQueryButtonActionPerformed
// TODO add your handling code here:
    inicializarVariables();
    String q = this.getSPARQLQuery();
    String r = this.getResultTextArea();

    this.consultaVacia(q, r);
    if(sinConsultas==false){
        this.consultaCompleta(q, r);
        continuar = consultaOK(q, r);
        if(continuar==true){
            this.validarConsulta(q);
            if(continuar==true){
                this.validarResultado(r);
            }
        } 
    }
    
    if(continuar==true){
        SparqlQueryOntology query = new SparqlQueryOntology(q,r);
        SparqlQueryOntology querySig = listaDeConsultas.get(posListQuerysSel-1);
        if(posListQuerysSel==listaDeConsultas.size()){
           listaDeConsultas.add(query); 
           this.prepararNuevaConsultaCompleta(querySig);
           sigQueryButton.setEnabled(true);
        }else{
            this.reemplazarConsulta(query, posListQuerysSel);
            this.prepararNuevaConsultaCompleta(querySig);
            sigQueryButton.setEnabled(true);
        }
        posListQuerysSel--; 
        if(posListQuerysSel==0){
            antQueryButton.setEnabled(false);
        }
    }   
}//GEN-LAST:event_antQueryButtonActionPerformed

private void sigQueryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigQueryButtonActionPerformed
// TODO add your handling code here:
    inicializarVariables();
    String q = this.getSPARQLQuery();
    String r = this.getResultTextArea();
    this.consultaVacia(q, r);
    if(sinConsultas==false){
        this.consultaCompleta(q, r);
        continuar = consultaOK(q, r);
        if(continuar==true){
            this.validarConsulta(q);
            if(continuar==true){
                this.validarResultado(r);
            }
        } 
    }
    if(continuar==true){ 
        SparqlQueryOntology query = new SparqlQueryOntology(q,r);
        this.reemplazarConsulta(query, posListQuerysSel);
        SparqlQueryOntology querySig = listaDeConsultas.get(posListQuerysSel+1);
        this.prepararNuevaConsultaCompleta(querySig);
        posListQuerysSel++; 
        if(posListQuerysSel==listaDeConsultas.size()-1){
            sigQueryButton.setEnabled(false);
        }
        if(posListQuerysSel<listaDeConsultas.size()){
            antQueryButton.setEnabled(true);
        }
    }   
}//GEN-LAST:event_sigQueryButtonActionPerformed

private void limpiarResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarResultButtonActionPerformed
// TODO add your handling code here:
    this.setResultTextArea("");
}//GEN-LAST:event_limpiarResultButtonActionPerformed

private void borrarConsultaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarConsultaJButtonActionPerformed
// TODO add your handling code here:
    inicializarVariables();
    if(listaDeConsultas.size()==0 || (this.getSPARQLQuery().equals("") && this.getResultTextArea().equals(""))){
        JOptionPane.showMessageDialog(this.getParent(),"No hay ninguna consulta que borrar",
        "Warning Message",JOptionPane.WARNING_MESSAGE);
    }else if(listaDeConsultas.size()==1){
        this.prepararNuevaConsultaVacia();
        setListaDeConsultas(new ArrayList<SparqlQueryOntology>());
        setPosListQuerysSel(0);
    }else{
        if(posListQuerysSel==listaDeConsultas.size()-1){
            SparqlQueryOntology querySig = listaDeConsultas.get(posListQuerysSel-1);
            listaDeConsultas.remove(posListQuerysSel);
            this.prepararNuevaConsultaCompleta(querySig);
            sigQueryButton.setEnabled(false);
            posListQuerysSel--;
        
        }else{
            SparqlQueryOntology querySig = listaDeConsultas.get(posListQuerysSel+1);
            this.prepararNuevaConsultaCompleta(querySig);
            listaDeConsultas.remove(posListQuerysSel);
        }
        if(posListQuerysSel==listaDeConsultas.size()-1){
            sigQueryButton.setEnabled(false);
        }
        if(listaDeConsultas.size()==1){
            sigQueryButton.setEnabled(false);
            antQueryButton.setEnabled(false);
        } 
    }
    
    
}//GEN-LAST:event_borrarConsultaJButtonActionPerformed

private void formatosPermitidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatosPermitidosActionPerformed
// TODO add your handling code here:
    FormatTestsJDialog format = new FormatTestsJDialog(frame,true,5);
    format.setLocationRelativeTo(this);
    format.setModal(false);
    format.setVisible(true);
}//GEN-LAST:event_formatosPermitidosActionPerformed

private void guardarJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
// TODO add your handling code here:
    guardarTest();
}                                              

private void guardarEjecutarJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                       
// TODO add your handling code here:
    saveTest = new SaveTest();
    testcase = new OntologyTestCase();
    resultTests = new ResultTests();
    testresult = new OntologyTestResult();  
    if(continuar==true){
        if(continuarSinInstancias==true){
            guardarYEjecutarTest();
        }else{
            addInst = new AddInstancesClasPropJDialog(this,true,this.getScenario());
            addInst.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
            addInst.setVisible(true);
        }
    }
}                                                      

private void ejecutarJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
// TODO add your handling code here:
    setSoloEjectuar(true);
    saveTest = new SaveTest();
    testcase = new OntologyTestCase();
    resultTests = new ResultTests();
    testresult = new OntologyTestResult();
    prepararGuardar();
    if(continuar==true){
        if(continuarSinInstancias==true){
            ejecutar(0);
        }else{
            addInst = new AddInstancesClasPropJDialog(this,true,this.getScenario());
            addInst.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
            addInst.setVisible(true);
        }
    }
}                                               

public boolean guardarTest(){
    prepararGuardar();
    if(continuar==true){
        if(continuarSinInstancias==true){
            guardar();
            return true;
        }else{
            addInst = new AddInstancesClasPropJDialog(this,true,this.getScenario());
            addInst.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
            addInst.setVisible(true);
            return false;
        }
    }else{
        return false;
    }   
}

public void guardarYEjecutarTest(){
    saveTest = new SaveTest();
    testcase = new OntologyTestCase();
    resultTests = new ResultTests();
    testresult = new OntologyTestResult();
    prepararGuardar();
    if(continuar==true){
        if(continuarSinInstancias==true){
            guardarYEjecutar();
        }else{
            addInst = new AddInstancesClasPropJDialog(this,true,this.getScenario());
            addInst.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
            addInst.setVisible(true);
        }
    }
}

public void ejecutar(int cuantos){
    if(isSoloEjectuar()==true){
        if(scenario.equals(this.getScenarioAEditar())==false){
            saveTest.replaceTestLocally(scenario);
        }else{
            saveTest.saveTestLocally(scenario);
        }
    }
    try{
        if(cuantos==0){
            testcase.runScenario(testresult, CollectionTest.getInstance(),getScenario());   
        }else if(cuantos==1){
            testcase.run(testresult, CollectionTest.getInstance());
        }
        JPanel panel = new TreeResults(testresult);
        resultTests.getContentPanelResults().add(panel);
        resultTests.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        resultTests.setVisible(true);
        resultTests.validate();
    } catch (ExceptionReadOntology ex) {
        new ExceptionReadOntology("La ontologia introducida no es valida." +
        "\nSolo pueden realizarse tests sobre documentos owl consistentes");
    }
}

public void guardarYEjecutar(){
    if(testYaExiste==true || getImportado()==true){
        if(scenario.equals(this.getScenarioAEditar())==false){
            Object[] options = {"Sobreescribir", "Cancelar"};
            int n = JOptionPane.showOptionDialog(frame, "El test ya existe o ha sido modificado. ¿Que desea hacer?", 
                    "Question", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            if (n == JOptionPane.YES_OPTION) {
                try {
                    saveTest.saveTestInMemory(scenario);
                    if(testYaExiste==true){
                        saveTest.replaceTestLocally(scenario);
                    }else{
                        saveTest.saveTestLocally(scenario);
                    }
                    setScenarioAEditar(new ScenarioTest(scenario));
                    setScenario(new ScenarioTest(scenario));
                    controlador.setTestSparqlGuardado(true);
                    JOptionPane.showMessageDialog(this.getParent(),"El test ha sido sobreescrito",
                    "Confirm Message",JOptionPane.INFORMATION_MESSAGE);
                    ejecutar(0);
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(this.getParent(),"El test no ha sido guardado",
                    "Error Message",JOptionPane.ERROR_MESSAGE);
                }
            }else if (n == JOptionPane.NO_OPTION) {
            }
        }else{
            controlador.setTestSparqlGuardado(true);
            JOptionPane.showMessageDialog(this.getParent(),"No se han producido cambios en el test",
            "Confirm Message",JOptionPane.INFORMATION_MESSAGE);
            ejecutar(0);
        }
        setImportado(false);
     }else{
        try {
            saveTest.saveTestInMemory(scenario);
            saveTest.saveTestLocally(scenario);
            setScenarioAEditar(new ScenarioTest(scenario));
            setScenario(new ScenarioTest(scenario));
            controlador.setTestSparqlGuardado(true);
            JOptionPane.showMessageDialog(this.getParent(),"El test ha sido guardado",
            "Confirm Message",JOptionPane.INFORMATION_MESSAGE);
            ejecutar(0);
        }catch (FileNotFoundException ex){
            JOptionPane.showMessageDialog(this.getParent(),"El test no ha sido guardado",
            "Error Message",JOptionPane.ERROR_MESSAGE);
        }
    }    
}

public void guardar(){
    saveTest = new SaveTest();
    if(testYaExiste==true || getImportado()==true){
        if(scenario.equals(this.getScenarioAEditar())==false){
            Object[] options = {"Sobreescribir", "Cancelar"};
            int n = JOptionPane.showOptionDialog(frame, "El test ya existe o ha sido modificado. ¿Que desea hacer?", 
                    "Question", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            if (n == JOptionPane.YES_OPTION) {
                try {
                    saveTest.saveTestInMemory(scenario);
                    if(testYaExiste==true){
                        saveTest.replaceTestLocally(scenario);
                    }else{
                        saveTest.saveTestLocally(scenario);
                    }
                    setScenarioAEditar(new ScenarioTest(scenario));
                    setScenario(new ScenarioTest(scenario));
                    controlador.setTestSparqlGuardado(true);
                    JOptionPane.showMessageDialog(this.getParent(),"El test ha sido sobreescrito",
                    "Confirm Message",JOptionPane.INFORMATION_MESSAGE);
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(this.getParent(),"El test no ha sido guardado",
                    "Error Message",JOptionPane.ERROR_MESSAGE);
                }
            }else if (n == JOptionPane.NO_OPTION) {
            }
        }else{
            controlador.setTestSparqlGuardado(true);
            JOptionPane.showMessageDialog(this.getParent(),"No se han producido cambios en el test",
            "Confirm Message",JOptionPane.INFORMATION_MESSAGE);
        }
        setImportado(false);
    }else{ 
        try {
            saveTest.saveTestInMemory(scenario);
            saveTest.saveTestLocally(scenario);
            setScenarioAEditar(new ScenarioTest(scenario));
            setScenario(new ScenarioTest(scenario));
            controlador.setTestSparqlGuardado(true);
            JOptionPane.showMessageDialog(this.getParent(),"El test ha sido guardado",
            "Confirm Message",JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this.getParent(),"El test no ha sido guardado",
            "Error Message",JOptionPane.ERROR_MESSAGE);
        }
    }
}

public void prepararGuardar(){
    inicializarVariables();
    String nombreTest = this.getTestNameTextField();
    String descTest = this.getTestDescTextArea();
    String query = this.getSPARQLQuery();
    String result = this.getResultTextArea();
    SparqlQueryOntology q = new SparqlQueryOntology(query,result);
    if(utils.testYaExiste(nombreTest)==true){
        testYaExiste=true;
    }
    if(testVacio(nombreTest)==true){
        testSinNombre=true;
    }
    //if(!this.inListSparqlQuerys(q)){
        this.consultaCompleta(query, result);
        this.consultaVacia(query, result);
        continuar = this.consultaOK(query, result);
        if(continuar==true){
            this.validarConsulta(query);
            if(continuar==true){
                this.validarResultado(result);
                if(continuar==true){
                    this.reemplazarConsulta(q, posListQuerysSel);
                }else{
                    JOptionPane.showMessageDialog(this,"El formato del resultado no es valido",
                    "Warning Message",JOptionPane.WARNING_MESSAGE);
                    continuar=false;
                }
            }
        }
    //}
    if(continuar==true){
        if(testSinNombre==false && listaDeConsultas.size()>0 && continuar==true){  
            preguntarSiContinuarSinInstancias(scenario);
            if(continuarSinInstancias==true){
                scenario.setDescripcion(descTest);
                scenario.setNombre(nombreTest);
                scenario.setSparqlQuerys(this.getListaDeConsultas()); 
            }
        }else if(testSinNombre==true){
                JOptionPane.showMessageDialog(this.getParent(),"El nombre del test es obligatorio",
                "Warning Message",JOptionPane.WARNING_MESSAGE);
                continuar=false;
        }else if(listaDeConsultas.size()==0 && testSinNombre==false){
            JOptionPane.showMessageDialog(this.getParent(),"Al menos debe introducir una consulta " +
            "para guardar el test.","Warning Message",JOptionPane.WARNING_MESSAGE);
            continuar=false;
        }
    }
}

public boolean testVacio(String nombre){
    if(nombre.equals("")){
        return true;
    }else{
        return false;
    }
}

public boolean preguntarSiContinuarSinInstancias(ScenarioTest scen){
    if(tieneInstanciasAsociadas(scen)==false){
        int n = JOptionPane.showConfirmDialog(comp, "El test no tiene instancias asociadas. " +
                "¿Desea continuar?", "Warning Message",JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.NO_OPTION){
            continuarSinInstancias=false;
        }else if(n == JOptionPane.YES_OPTION){
            continuarSinInstancias=true;
        }
    }

    return continuarSinInstancias;
}

public void inicializarVariables(){
    continuarSinInstancias=true;
    resultValido=true;
    queryValida=true;
    testSinNombre=false;
    testYaExiste=false;
    sinConsultas=false;
    continuar=true;
    ambosNecesarios=false;
}      

    public boolean inListSparqlQuerys(SparqlQueryOntology query){
        String queryq = query.getQuerySparql();
        String queryres = query.getResultexpected();
        SparqlQueryOntology sparql = this.getScenario().getSparqlQuerys().get(this.getPosListQuerysSel());
        String qquery = sparql.getQuerySparql();
        String qresult = sparql.getResultexpected();
        if(!qquery.equals(queryq) || !qresult.equals(queryres)){
            return false;
        }
        return true;
    }

    public boolean tieneInstanciasAsociadas(ScenarioTest scenario){
        Instancias inst = scenario.getInstancias();
        List<ClassInstances> clasI = inst.getClassInstances();
        List<PropertyInstances> propI = inst.getPropertyInstances();

        if(clasI.size()==0 && propI.size()==0){
            return false;
        }else{
            return true;
        }
    }
    
    public boolean pertenece(SparqlQueryOntology sparql){
        for(int i=0; i<getListaDeConsultas().size();i++){
            String query = getListaDeConsultas().get(i).getQuerySparql();
            String res = getListaDeConsultas().get(i).getResultexpected();
            if(query.equals(sparql.getQuerySparql()) && res.equals(sparql.getResultexpected())){
                return true;
            }
        }
        return false;
    }

    public JPanel getPanelTree() {
        return panelTree;
    }

    public void setPanelTree(JPanel aPanelTree) {
        panelTree = aPanelTree;
    }
    
    public List<SparqlQueryOntology> getListaDeConsultas() {
        return listaDeConsultas;
    }

    public void setListaDeConsultas(List<SparqlQueryOntology> aListaDeConsultas) {
        listaDeConsultas = aListaDeConsultas;
    }

    public String getResultTextArea() {
        return resultTextArea.getText();
    }

    public void setResultTextArea(String aResultTextArea) {
        resultTextArea.setText(aResultTextArea);
    }

    public String getSPARQLQuery() {
        return getSparqlTextArea().getText();
    }

    public void setSPARQLQuery(String aSparqlTextArea) {
        getSparqlTextArea().setText(aSparqlTextArea);
    }

    public String getTestDescTextArea() {
        return testDescTextArea.getText();
    }

    public void setTestDescTextArea(String aTestDescTextArea) {
        testDescTextArea.setText(aTestDescTextArea);
    }

    public String getTestNameTextField() {
        return testNameTextField.getText();
    }

    public void setTestNameTextField(String aTestNameTextField) {
        testNameTextField.setText(aTestNameTextField);
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public boolean isIsAntSelected() {
        return isAntSelected;
    }

    public void setIsAntSelected(boolean isAntSelected) {
        this.isAntSelected = isAntSelected;
    }

    public boolean isIsSigSelected() {
        return isSigSelected;
    }

    public void setIsSigSelected(boolean isSigSelected) {
        this.isSigSelected = isSigSelected;
    }

    public javax.swing.JButton getAntQueryButton() {
        return antQueryButton;
    }

    public  javax.swing.JButton getSigQueryButton() {
        return sigQueryButton;
    }

    public javax.swing.JTextArea getSparqlTextArea() {
        return sparqlTextArea;
    }

    public static boolean isSeleccionado() {
        return seleccionado;
    }

    public static void setSeleccionado(boolean aSeleccionado) {
        seleccionado = aSeleccionado;
    }

    public void setAntQueryButton(boolean state) {
        getAntQueryButton().setEnabled(state);
    }

    public void setSigQueryButton(boolean state) {
        getSigQueryButton().setEnabled(state);
    }

    public int getPosListQuerysSel() {
            return posListQuerysSel;
    }

    public void setPosListQuerysSel(int aPosListQuerysSel) {
        posListQuerysSel = aPosListQuerysSel;
    }

    public ScenarioTest getScenario() {
            return scenario;
        }

    public void setScenario(ScenarioTest scenario) {
        this.scenario = scenario;
    }

    public ScenarioTest getScenarioAEditar() {
        return scenarioAEditar;
    }

    public void setScenarioAEditar(ScenarioTest scenarioAEditar) {
        this.scenarioAEditar = scenarioAEditar;
    }

    public boolean getImportado() {
        return importado;
    }

    public void setImportado(boolean importado) {
        this.importado = importado;
    }
    
    public boolean isSoloEjectuar() {
        return soloEjectuar;
    }

    public void setSoloEjectuar(boolean soloEjectuar) {
        this.soloEjectuar = soloEjectuar;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton antQueryButton;
    private javax.swing.JButton borrarConsultaJButton;
    private javax.swing.JButton ejecutarJButton;
    private javax.swing.JButton formatosPermitidos;
    private javax.swing.JButton guardarEjecutarJButton;
    private javax.swing.JButton guardarJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JButton limpiarResultButton;
    private javax.swing.JButton nuevaConsultaButton;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JButton sigQueryButton;
    private javax.swing.JTextArea sparqlTextArea;
    private javax.swing.JTextArea testDescTextArea;
    private javax.swing.JTextField testNameTextField;
    // End of variables declaration//GEN-END:variables

}
