/*
 * MainApplication.java
 *
 * Created on 11 de septiembre de 2008, 16:32
 */

package code.google.com.p.ontologytesting.guiNew;

import code.google.com.p.ontologytesting.exceptions.ExceptionReadOntology;
import code.google.com.p.ontologytesting.guiNew.ControladorTests;
import code.google.com.p.ontologytesting.controller.Auxiliar;
import code.google.com.p.ontologytesting.model.*;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.beans.XMLDecoder;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author  saruskas
 */
public class MainApplication extends javax.swing.JFrame {

    private static CollectionTest collection;
    private AddOntologyJDialog ontologia;
    private JFileChooser filechooser;
    private MenuOperations menuOp;
    private static String proyecto;
    private Component frame;
    private XMLDecoder decoder;
    private AddInstancesClasPropJDialog addInst;
    private Instancias instancias;
    private ScenarioTest scenario;
    private OntologyTestCase testcase;
    private ResultTests resultTests;
    private OntologyTestResult testresult;
    private SeeTestJDialog seeTest;
    

    /** Creates new form MainApplication */
    public MainApplication() {
        initComponents();
        this.setTitle("EVALUADOR DE ONTOLOGIAS");
        this.setSize(new Dimension(895,720));
        ControladorTests.inicializarGuardados();
        ControladorTests.inicializarSeleccionados();
        contentTestsJPanel.setLayout(new BorderLayout());
        collection = new CollectionTest();
        collection.setNamespace("http://www.owl-ontologies.com/family.owl#");
        collection.setOntology("C:\\Users\\saruskas\\Desktop\\Proyecto Menu\\ontologyTestGUI\\data\\family.owl");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentTestsJPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        proyectoMenu = new javax.swing.JMenu();
        nuevoProyecto = new javax.swing.JMenuItem();
        abrirProyecto = new javax.swing.JMenuItem();
        guardarProyecto = new javax.swing.JMenuItem();
        guardarProyectoComo = new javax.swing.JMenuItem();
        salirProyecto = new javax.swing.JMenuItem();
        testsSimplesMenu = new javax.swing.JMenu();
        nuevoTestSimple = new javax.swing.JMenu();
        nuevoTestInst = new javax.swing.JMenuItem();
        nuevoTestRec = new javax.swing.JMenuItem();
        nuevoTestReal = new javax.swing.JMenuItem();
        nuevoTestSat = new javax.swing.JMenuItem();
        nuevoTestCla = new javax.swing.JMenuItem();
        importarTestSimple = new javax.swing.JMenuItem();
        editarTestSimple = new javax.swing.JMenuItem();
        verTestMenuItem = new javax.swing.JMenuItem();
        testsSparqlMenu = new javax.swing.JMenu();
        nuevoTestSparql = new javax.swing.JMenuItem();
        importarTestSparql = new javax.swing.JMenuItem();
        editarTestSparql = new javax.swing.JMenuItem();
        verTestSparql = new javax.swing.JMenuItem();
        instanciasMenu = new javax.swing.JMenu();
        nuevoInstancias = new javax.swing.JMenuItem();
        importarInstancias = new javax.swing.JMenuItem();
        editarInstancias = new javax.swing.JMenuItem();
        verInstancias = new javax.swing.JMenuItem();
        ejecutarMenu = new javax.swing.JMenu();
        ejectuarTests = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout contentTestsJPanelLayout = new javax.swing.GroupLayout(contentTestsJPanel);
        contentTestsJPanel.setLayout(contentTestsJPanelLayout);
        contentTestsJPanelLayout.setHorizontalGroup(
            contentTestsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        contentTestsJPanelLayout.setVerticalGroup(
            contentTestsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        proyectoMenu.setText("Proyecto");

        nuevoProyecto.setText("Nuevo");
        nuevoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoProyectoActionPerformed(evt);
            }
        });
        proyectoMenu.add(nuevoProyecto);

        abrirProyecto.setText("Abrir");
        proyectoMenu.add(abrirProyecto);

        guardarProyecto.setText("Guardar");
        proyectoMenu.add(guardarProyecto);

        guardarProyectoComo.setText("Guardar como");
        proyectoMenu.add(guardarProyectoComo);

        salirProyecto.setText("Salir");
        salirProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirProyectoActionPerformed(evt);
            }
        });
        proyectoMenu.add(salirProyecto);

        menuBar.add(proyectoMenu);

        testsSimplesMenu.setText("Tests Simples");

        nuevoTestSimple.setText("Nuevo");

        nuevoTestInst.setText("Test de Instanciación");
        nuevoTestInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoTestInstActionPerformed(evt);
            }
        });
        nuevoTestSimple.add(nuevoTestInst);

        nuevoTestRec.setText("Test de Recuperación");
        nuevoTestRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoTestRecActionPerformed(evt);
            }
        });
        nuevoTestSimple.add(nuevoTestRec);

        nuevoTestReal.setText("Test de Realización");
        nuevoTestReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoTestRealActionPerformed(evt);
            }
        });
        nuevoTestSimple.add(nuevoTestReal);

        nuevoTestSat.setText("Test de Satisfactibilidad");
        nuevoTestSat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoTestSatActionPerformed(evt);
            }
        });
        nuevoTestSimple.add(nuevoTestSat);

        nuevoTestCla.setText("Test de Clasificación");
        nuevoTestCla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoTestClaActionPerformed(evt);
            }
        });
        nuevoTestSimple.add(nuevoTestCla);

        testsSimplesMenu.add(nuevoTestSimple);

        importarTestSimple.setText("Importar");
        importarTestSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarTestSimpleActionPerformed(evt);
            }
        });
        testsSimplesMenu.add(importarTestSimple);

        editarTestSimple.setText("Editar");
        editarTestSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTestSimpleActionPerformed(evt);
            }
        });
        testsSimplesMenu.add(editarTestSimple);

        verTestMenuItem.setText("Ver");
        verTestMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTestMenuItemActionPerformed(evt);
            }
        });
        testsSimplesMenu.add(verTestMenuItem);

        menuBar.add(testsSimplesMenu);

        testsSparqlMenu.setText("Tests SPARQL");

        nuevoTestSparql.setText("Nuevo");
        nuevoTestSparql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoTestSparqlActionPerformed(evt);
            }
        });
        testsSparqlMenu.add(nuevoTestSparql);

        importarTestSparql.setText("Importar");
        importarTestSparql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarTestSparqlActionPerformed(evt);
            }
        });
        testsSparqlMenu.add(importarTestSparql);

        editarTestSparql.setText("Editar");
        editarTestSparql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTestSparqlActionPerformed(evt);
            }
        });
        testsSparqlMenu.add(editarTestSparql);

        verTestSparql.setText("Ver");
        testsSparqlMenu.add(verTestSparql);

        menuBar.add(testsSparqlMenu);

        instanciasMenu.setText("Instancias");

        nuevoInstancias.setText("Nuevo");
        nuevoInstancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoInstanciasActionPerformed(evt);
            }
        });
        instanciasMenu.add(nuevoInstancias);

        importarInstancias.setText("Importar");
        importarInstancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarInstanciasActionPerformed(evt);
            }
        });
        instanciasMenu.add(importarInstancias);

        editarInstancias.setText("Editar");
        editarInstancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarInstanciasActionPerformed(evt);
            }
        });
        instanciasMenu.add(editarInstancias);

        verInstancias.setText("Ver");
        verInstancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verInstanciasActionPerformed(evt);
            }
        });
        instanciasMenu.add(verInstancias);

        menuBar.add(instanciasMenu);

        ejecutarMenu.setText("Ejecutar");

        ejectuarTests.setText("Todos los Test");
        ejectuarTests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejectuarTestsActionPerformed(evt);
            }
        });
        ejecutarMenu.add(ejectuarTests);

        menuBar.add(ejecutarMenu);

        helpMenu.setText("Help");

        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentTestsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentTestsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirProyectoActionPerformed
        System.exit(0);
}//GEN-LAST:event_salirProyectoActionPerformed

private void nuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoProyectoActionPerformed
// TODO add your handling code here:
    filechooser = new JFileChooser();
    filechooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
    int option = filechooser.showOpenDialog(this);
      if (option == JFileChooser.APPROVE_OPTION) {
        setProyecto(filechooser.getSelectedFile().getAbsolutePath());
        collection = new CollectionTest();
        ontologia = new AddOntologyJDialog(this,true);
        ontologia.setVisible(true);
        if(ontologia.getOntologiaAsociada()==true){
            this.getInstanciasMenu().setEnabled(true);
            this.getTestsSimplesMenu().setEnabled(true);
            this.getTestsSparqlMenu().setEnabled(true);
            this.getEjecutarMenu().setEnabled(true);
        }
      }
}//GEN-LAST:event_nuevoProyectoActionPerformed

private void nuevoTestInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoTestInstActionPerformed
// TODO add your handling code here:
    if(ControladorTests.algunTestSinGuardar()==false){
        ControladorTests.inicializarGuardados();
        ControladorTests.inicializarSeleccionados();
        ControladorTests.setTestInstGuardado(false);
        ControladorTests.setTestInstSelect(true);
        aniadirTestsInst();
    }else{
        int n = JOptionPane.showConfirmDialog(this, "¿Guardar los cambios realizados al test?", 
                "Guardar Tests",JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION){
                if(guardarAntesDeSeguir()){
                    ControladorTests.inicializarGuardados();
                    ControladorTests.inicializarSeleccionados();
                    ControladorTests.setTestInstGuardado(false);
                    ControladorTests.setTestInstSelect(true);
                    aniadirTestsInst();
                }
            }else{
                ControladorTests.inicializarGuardados();
                ControladorTests.inicializarSeleccionados();
                ControladorTests.setTestInstGuardado(false);
                ControladorTests.setTestInstSelect(true);
                aniadirTestsInst();
            }
    }
}//GEN-LAST:event_nuevoTestInstActionPerformed

private void importarTestSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarTestSimpleActionPerformed
// TODO add your handling code here:        
    menuOp = new MenuOperations();
    try{
        if(menuOp.importarTest()){
            JOptionPane.showMessageDialog(this,"El test se ha importado correctamente",
            "Information Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }catch(FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"No se ha importado el test",//GEN-LAST:event_importarTestSimpleActionPerformed
            "Error Message",JOptionPane.ERROR_MESSAGE);
    }
}                                                  

private void editarTestSimpleActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    try {
        editarTests();
    } catch (FileNotFoundException ex) {
         JOptionPane.showMessageDialog(this,"No se puede abrir el test para su edicion",                                                  
            "Error Message",JOptionPane.ERROR_MESSAGE);
    }
}                                                

private void importarTestSparqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarTestSparqlActionPerformed
// TODO add your handling code here:
   menuOp = new MenuOperations();
    try{
        if(menuOp.importarTest()){
            JOptionPane.showMessageDialog(this,"El test se ha importado correctamente",
            "Information Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }catch(FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"No se ha importado el test",                                                  
            "Error Message",JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_importarTestSparqlActionPerformed

private void nuevoInstanciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoInstanciasActionPerformed
// TODO add your handling code here:
    int sel = ControladorTests.testSeleccionado();
    addInst = new AddInstancesClasPropJDialog(this,true,sel);
    addInst.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    addInst.setVisible(true);
}//GEN-LAST:event_nuevoInstanciasActionPerformed

private void importarInstanciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarInstanciasActionPerformed
// TODO add your handling code here:
    importarInstancias();
}//GEN-LAST:event_importarInstanciasActionPerformed

private void editarInstanciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarInstanciasActionPerformed
// TODO add your handling code here:
    editarInstancias();
}//GEN-LAST:event_editarInstanciasActionPerformed

private void verInstanciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verInstanciasActionPerformed
// TODO add your handling code here:
    filechooser = new JFileChooser(MainApplication.getProyecto());                                               
    int option = filechooser.showOpenDialog(frame);
    if (option == JFileChooser.APPROVE_OPTION) {
        File selectedFile = filechooser.getSelectedFile();
        String nameFile = selectedFile.getPath();
        try {
            decoder = new XMLDecoder(new BufferedInputStream(new FileInputStream(nameFile)));
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"No se puede leer el fichero",
            "Error Message",JOptionPane.ERROR_MESSAGE);
        }
        Instancias inst = (Instancias) decoder.readObject();
        seeTest = new SeeTestJDialog(this, false, inst);
        seeTest.setVisible(true);
    }  
}//GEN-LAST:event_verInstanciasActionPerformed

private void nuevoTestRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoTestRecActionPerformed
// TODO add your handling code here:
    if(ControladorTests.algunTestSinGuardar()==false){
        ControladorTests.inicializarGuardados();
        ControladorTests.inicializarSeleccionados();
        ControladorTests.setTestRetGuardado(false);
        ControladorTests.setTestRetSelect(true);
        aniadirTestsRet();
    }else{
        int n = JOptionPane.showConfirmDialog(this, "¿Guardar los cambios realizados al test?", 
                "Guardar Tests",JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION){
                if(guardarAntesDeSeguir()){
                    ControladorTests.inicializarGuardados();
                    ControladorTests.inicializarSeleccionados();
                    ControladorTests.setTestRetGuardado(false);
                    ControladorTests.setTestRetSelect(true);
                    aniadirTestsRet();
                }
            }else{
                ControladorTests.inicializarGuardados();
                ControladorTests.inicializarSeleccionados();
                ControladorTests.setTestRetGuardado(false);
                ControladorTests.setTestRetSelect(true);
                aniadirTestsRet();
            }
    }
}//GEN-LAST:event_nuevoTestRecActionPerformed

public boolean guardarAntesDeSeguir(){
    int sel = ControladorTests.testSeleccionado();
    boolean seguir=false;
    if(sel==0 || sel==3){
        seguir = Auxiliar.getTestSimpleInstSat().guardarTest();
    }else if(sel==1 || sel==4){
        seguir = Auxiliar.getTestSimpleRetClas().guardarTest();
    }else if(sel==2){
        seguir = Auxiliar.getTestSimpleReal().guardarTest();
    }else if(sel==5){

    }
    return seguir;
}

private void nuevoTestRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoTestRealActionPerformed
// TODO add your handling code here:
    if(ControladorTests.algunTestSinGuardar()==false || getContentTestsJPanel().getComponentCount()==0){
        ControladorTests.inicializarGuardados();
        ControladorTests.inicializarSeleccionados();
        ControladorTests.setTestRealGuardado(false);
        ControladorTests.setTestRealSelect(true);
        aniadirTestsReal();
    }else{
        int n = JOptionPane.showConfirmDialog(this, "¿Guardar los cambios realizados al test?", 
                "Guardar Tests",JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION){
                if(guardarAntesDeSeguir()){
                    ControladorTests.inicializarGuardados();
                    ControladorTests.inicializarSeleccionados();
                    ControladorTests.setTestRealGuardado(false);
                    ControladorTests.setTestRealSelect(true);
                    aniadirTestsReal();
                }
            }else{
                ControladorTests.inicializarGuardados();
                ControladorTests.inicializarSeleccionados();
                ControladorTests.setTestRealGuardado(false);
                ControladorTests.setTestRealSelect(true);
                aniadirTestsReal();
            }
    }
}//GEN-LAST:event_nuevoTestRealActionPerformed

private void nuevoTestSatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoTestSatActionPerformed
// TODO add your handling code here:
    if(ControladorTests.algunTestSinGuardar()==false || getContentTestsJPanel().getComponentCount()==0){
        ControladorTests.inicializarGuardados();
        ControladorTests.inicializarSeleccionados();
        ControladorTests.setTestSatGuardado(false);
        ControladorTests.setTestSatSelect(true);
        aniadirTestsSat();
    }else{
        int n = JOptionPane.showConfirmDialog(this, "¿Guardar los cambios realizados al test?", 
                "Guardar Tests",JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION){
                if(guardarAntesDeSeguir()){
                    ControladorTests.inicializarGuardados();
                    ControladorTests.inicializarSeleccionados();
                    ControladorTests.setTestSatGuardado(false);
                    ControladorTests.setTestSatSelect(true);
                    aniadirTestsSat();
                }
            }else{
                ControladorTests.inicializarGuardados();
                ControladorTests.inicializarSeleccionados();
                ControladorTests.setTestSatGuardado(false);
                ControladorTests.setTestSatSelect(true);
                aniadirTestsSat();
            }
    }
}//GEN-LAST:event_nuevoTestSatActionPerformed

private void nuevoTestClaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoTestClaActionPerformed
// TODO add your handling code here:
    if(ControladorTests.algunTestSinGuardar()==false || getContentTestsJPanel().getComponentCount()==0){
        ControladorTests.inicializarGuardados();
        ControladorTests.inicializarSeleccionados();
        ControladorTests.setTestClasGuardado(false);
        ControladorTests.setTestClasSelect(true);
        aniadirTestsClas();
    }else{
        int n = JOptionPane.showConfirmDialog(this, "¿Guardar los cambios realizados al test?", 
                "Guardar Tests",JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION){
                if(guardarAntesDeSeguir()){
                    ControladorTests.inicializarGuardados();
                    ControladorTests.inicializarSeleccionados();
                    ControladorTests.setTestClasGuardado(false);
                    ControladorTests.setTestClasSelect(true);
                    aniadirTestsClas();
                }
            }else{
                ControladorTests.inicializarGuardados();
                ControladorTests.inicializarSeleccionados();
                ControladorTests.setTestClasGuardado(false);
                ControladorTests.setTestClasSelect(true);
                aniadirTestsClas();
            }
    }
}//GEN-LAST:event_nuevoTestClaActionPerformed

private void ejectuarTestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejectuarTestsActionPerformed
// TODO add your handling code here:
  
    if(MainApplication.getCollection().getScenariotest().size()==0){
        JOptionPane.showMessageDialog(frame,"No tiene ningun test para ejecutar",
        "Warning Message",JOptionPane.WARNING_MESSAGE);
    }else{
            try{
	testcase = new OntologyTestCase();//GEN-LAST:event_ejectuarTestsActionPerformed
            resultTests = new ResultTests();
            testresult = new OntologyTestResult();
            testcase.run(testresult, MainApplication.getCollection());
            JPanel panel = new TreeResults(testresult);
            resultTests.getContentPanelResults().add(panel);
            resultTests.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
            resultTests.setVisible(true);
            resultTests.validate();
        } catch (ExceptionReadOntology ex) {
            new ExceptionReadOntology();
        }
    }
}
    
private void verTestMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTestMenuItemActionPerformed
// TODO add your handling code here:
    filechooser = new JFileChooser(MainApplication.getProyecto());//GEN-LAST:event_verTestMenuItemActionPerformed
    int option = filechooser.showOpenDialog(frame);
    if (option == JFileChooser.APPROVE_OPTION) {
        File selectedFile = filechooser.getSelectedFile();
        String nameFile = selectedFile.getPath();
        try {
            decoder = new XMLDecoder(new BufferedInputStream(new FileInputStream(nameFile)));
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"No se puede leer el fichero",
            "Error Message",JOptionPane.ERROR_MESSAGE);
        }
        ScenarioTest s = (ScenarioTest) decoder.readObject();
        seeTest = new SeeTestJDialog(this, false, s);
        seeTest.setVisible(true);
    }
}
private void nuevoTestSparqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoTestSparqlActionPerformed
// TODO add your handling code here:
if(ControladorTests.algunTestSinGuardar()==false || getContentTestsJPanel().getComponentCount()==0){//GEN-LAST:event_nuevoTestSparqlActionPerformed
    ControladorTests.inicializarGuardados();
    ControladorTests.inicializarSeleccionados();
    ControladorTests.setTestSparqlGuardado(false);
    ControladorTests.setTestSparqlSelect(true);
    aniadirTestsSparql();
}else{
    int n = JOptionPane.showConfirmDialog(this, "¿Guardar los cambios realizados al test?", 
            "Guardar Tests",JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION){
            if(guardarAntesDeSeguir()){
                ControladorTests.inicializarGuardados();
                ControladorTests.inicializarSeleccionados();
                ControladorTests.setTestClasGuardado(false);
                ControladorTests.setTestClasSelect(true);
                aniadirTestsSparql();
            }
        }else{
            ControladorTests.inicializarGuardados();
            ControladorTests.inicializarSeleccionados();
            ControladorTests.setTestClasGuardado(false);
            ControladorTests.setTestClasSelect(true);
            aniadirTestsSparql();
        }
}
}

private void editarTestSparqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarTestSparqlActionPerformed
// TODO add your handling code here:
    try {//GEN-LAST:event_editarTestSparqlActionPerformed
        editarTests();
    } catch (FileNotFoundException ex) {
         JOptionPane.showMessageDialog(this,"No se puede abrir el test para su edicion",                                                  
            "Error Message",JOptionPane.ERROR_MESSAGE);
    }
}

                                       
public void aniadirTestsInst(){ 
    int cont = getContentTestsJPanel().getComponentCount();
    if(cont==0){
        getContentTestsJPanel().add(new TestSimpleInstSat(0),BorderLayout.NORTH);
    }else{
        getContentTestsJPanel().remove(0);
        getContentTestsJPanel().add(new TestSimpleInstSat(0),BorderLayout.NORTH);
    }
    getContentTestsJPanel().getParent().validate();
}

public void aniadirTestsSat(){ 
    int cont = getContentTestsJPanel().getComponentCount();
    if(cont==0){
        getContentTestsJPanel().add(new TestSimpleInstSat(3),BorderLayout.NORTH);
    }else{
        getContentTestsJPanel().remove(0);
        getContentTestsJPanel().add(new TestSimpleInstSat(3),BorderLayout.NORTH);
    }
    getContentTestsJPanel().getParent().validate();
}

public void aniadirTestsRet(){ 
    int cont = getContentTestsJPanel().getComponentCount();
    if(cont==0){
        getContentTestsJPanel().add(new TestSimpleRetClas(1),BorderLayout.CENTER);
    }else{
        getContentTestsJPanel().remove(0);
        getContentTestsJPanel().add(new TestSimpleRetClas(1),BorderLayout.CENTER);
    }
    getContentTestsJPanel().getParent().validate();
}

public void aniadirTestsClas(){ 
    int cont = getContentTestsJPanel().getComponentCount();
    if(cont==0){
        getContentTestsJPanel().add(new TestSimpleRetClas(4),BorderLayout.NORTH);
    }else{
        getContentTestsJPanel().remove(0);
        getContentTestsJPanel().add(new TestSimpleRetClas(4),BorderLayout.NORTH);
    }
    getContentTestsJPanel().getParent().validate();
}

public void aniadirTestsSparql(){ 
    int cont = getContentTestsJPanel().getComponentCount();
    if(cont==0){
        getContentTestsJPanel().add(new AddSPARQLJPanel(5),BorderLayout.NORTH);
    }else{
        getContentTestsJPanel().remove(0);
        getContentTestsJPanel().add(new AddSPARQLJPanel(5),BorderLayout.NORTH);
    }
    getContentTestsJPanel().getParent().validate();
}

public void aniadirTestsReal(){ 
    int cont = getContentTestsJPanel().getComponentCount();
    if(cont==0){
        getContentTestsJPanel().add(new TestSimpleReal(2),BorderLayout.NORTH);
    }else{
        getContentTestsJPanel().remove(0);
        getContentTestsJPanel().add(new TestSimpleReal(2),BorderLayout.NORTH);
    }
    getContentTestsJPanel().getParent().validate();
}

public void editarTests() throws FileNotFoundException{
    ControladorTests.inicializarGuardados();
    ControladorTests.inicializarSeleccionados();
    filechooser = new JFileChooser(MainApplication.getProyecto());
    int option = filechooser.showOpenDialog(this);
    if (option == JFileChooser.APPROVE_OPTION) {
        File selectedFile = filechooser.getSelectedFile();
        String nameFile = selectedFile.getPath();
        decoder = new XMLDecoder(new BufferedInputStream(new FileInputStream(nameFile)));
        ScenarioTest s = (ScenarioTest) decoder.readObject();
        String tipoTest = s.getTestName();
        if(tipoTest.equals("Instanciacion")){
            ControladorTests.setTestInstGuardado(false);
            ControladorTests.setTestInstSelect(true);
            TestSimpleInstSat testInst = new TestSimpleInstSat(0, s);
            int cont = getContentTestsJPanel().getComponentCount();
            if(cont==0){
                getContentTestsJPanel().add(testInst,BorderLayout.NORTH);
            }else{
                getContentTestsJPanel().remove(0);
                getContentTestsJPanel().add(testInst,BorderLayout.NORTH);
            }
            getContentTestsJPanel().getParent().validate();
        }else if(tipoTest.equals("Retrieval")){
            ControladorTests.setTestRetGuardado(false);
            ControladorTests.setTestRetSelect(true);
            TestSimpleRetClas testInst = new TestSimpleRetClas(1, s);
            int cont = getContentTestsJPanel().getComponentCount();
            if(cont==0){
                getContentTestsJPanel().add(testInst,BorderLayout.NORTH);
            }else{
                getContentTestsJPanel().remove(0);
                getContentTestsJPanel().add(testInst,BorderLayout.NORTH);
            }
            getContentTestsJPanel().getParent().validate();
        }else if(tipoTest.equals("Realizacion")){
            ControladorTests.setTestRealGuardado(false);
            ControladorTests.setTestRealSelect(true);
            TestSimpleReal testInst = new TestSimpleReal(2, s);
            int cont = getContentTestsJPanel().getComponentCount();
            if(cont==0){
                getContentTestsJPanel().add(testInst,BorderLayout.NORTH);
            }else{
                getContentTestsJPanel().remove(0);
                getContentTestsJPanel().add(testInst,BorderLayout.NORTH);
            }
            getContentTestsJPanel().getParent().validate();

        }else if(tipoTest.equals("Satisfactibilidad")){
            ControladorTests.setTestSatGuardado(false);
            ControladorTests.setTestSatSelect(true);
            TestSimpleInstSat testInst = new TestSimpleInstSat(3, s);
            int cont = getContentTestsJPanel().getComponentCount();
            if(cont==0){
                getContentTestsJPanel().add(testInst,BorderLayout.NORTH);
            }else{
                getContentTestsJPanel().remove(0);
                getContentTestsJPanel().add(testInst,BorderLayout.NORTH);
            }
            getContentTestsJPanel().getParent().validate();

        }else if(tipoTest.equals("Clasificacion")){
            ControladorTests.setTestClasGuardado(false);
            ControladorTests.setTestClasSelect(true);
            TestSimpleRetClas testInst = new TestSimpleRetClas(4, s);
            int cont = getContentTestsJPanel().getComponentCount();
            if(cont==0){
                getContentTestsJPanel().add(testInst,BorderLayout.NORTH);
            }else{
                getContentTestsJPanel().remove(0);
                getContentTestsJPanel().add(testInst,BorderLayout.NORTH);
            }
            getContentTestsJPanel().getParent().validate();
        }else if(tipoTest.equals("sparql")){
            ControladorTests.setTestSparqlGuardado(false);
            ControladorTests.setTestSparqlSelect(true);
            AddSPARQLJPanel testSparql = new AddSPARQLJPanel(5, s);
            int cont = getContentTestsJPanel().getComponentCount();
            if(cont==0){
                getContentTestsJPanel().add(testSparql,BorderLayout.NORTH);
            }else{
                getContentTestsJPanel().remove(0);
                getContentTestsJPanel().add(testSparql,BorderLayout.NORTH);
            }
            getContentTestsJPanel().getParent().validate();
        }
    }   
}

public void editarInstancias(){
    int cont = getContentTestsJPanel().getComponentCount();
    if(cont==0){
        //Aqui abrir las instancia para editarlas
        //JOptionPane.showMessageDialog(this,"No hay ningun test abierto para editar sus instancias",
        //"Information Message",JOptionPane.INFORMATION_MESSAGE);
    }else{
        editarInstanciasAsociadasTest();
    }
}

public void importarInstancias(){
    int cont = getContentTestsJPanel().getComponentCount();
    if(cont==0){
        JOptionPane.showMessageDialog(this,"No hay ningun test abierto al que importar las instancias",
        "Warning Message",JOptionPane.INFORMATION_MESSAGE);
    }else{
        int sel = ControladorTests.testSeleccionado();
        if(sel==0 || sel==3){
            scenario = Auxiliar.getTestSimpleInstSat().getScenario();
        }else if(sel==1 || sel==4){
            scenario = Auxiliar.getTestSimpleRetClas().getScenario();
        }else if(sel==2){
            scenario = Auxiliar.getTestSimpleReal().getScenario();
        }else if(sel==5){
            scenario = Auxiliar.getTestSparql().getScenario();
        } 
        menuOp = new MenuOperations();
        try{
            if(menuOp.importarInstancias(scenario)){
                JOptionPane.showMessageDialog(this,"Las instancias se ha importado correctamente",
                "Information Message",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"No se ha importado el test",                                                  
            "Error Message",JOptionPane.ERROR_MESSAGE);
        } 
    }
}

public void editarInstanciasAsociadasTest(){
    int sel = ControladorTests.testSeleccionado();
    if(sel==0 || sel==3){
        instancias = Auxiliar.getTestSimpleInstSat().getScenario().getInstancias();
    }else if(sel==1 || sel==4){
        instancias = Auxiliar.getTestSimpleRetClas().getScenario().getInstancias();
    }else if(sel==2){
        instancias = Auxiliar.getTestSimpleReal().getScenario().getInstancias();
    }else if(sel==5){
        instancias = Auxiliar.getTestSparql().getScenario().getInstancias();
    }
    if(instancias.getPropertyInstances().size()==0 &&  instancias.getClassInstances().size()==0){
        JOptionPane.showMessageDialog(this,"Este test no tiene instancias asociadas",
        "Information Message",JOptionPane.INFORMATION_MESSAGE);
    }else{
        addInst = new AddInstancesClasPropJDialog(this,true,instancias,sel);
        addInst.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        addInst.setVisible(true);
    }
}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainApplication().setVisible(true);
            }
        });
    }
    
    public static CollectionTest getCollection() {
        return collection;
    }
    
    public javax.swing.JMenu getInstanciasMenu() {
        return instanciasMenu;
    }

    public javax.swing.JMenu getTestsSimplesMenu() {
        return testsSimplesMenu;
    }

    public javax.swing.JMenu getTestsSparqlMenu() {
        return testsSparqlMenu;
    }
    
    public javax.swing.JPanel getContentTestsJPanel() {
        return contentTestsJPanel;
    }
    
    public static String getProyecto() {
        return proyecto;
    }

    public static void setProyecto(String aProyecto) {
        proyecto = aProyecto;
    }
    
    public javax.swing.JMenu getEjecutarMenu() {
        return ejecutarMenu;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem abrirProyecto;
    private javax.swing.JPanel contentTestsJPanel;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem editarInstancias;
    private javax.swing.JMenuItem editarTestSimple;
    private javax.swing.JMenuItem editarTestSparql;
    private javax.swing.JMenuItem ejectuarTests;
    private javax.swing.JMenu ejecutarMenu;
    private javax.swing.JMenuItem guardarProyecto;
    private javax.swing.JMenuItem guardarProyectoComo;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem importarInstancias;
    private javax.swing.JMenuItem importarTestSimple;
    private javax.swing.JMenuItem importarTestSparql;
    private javax.swing.JMenu instanciasMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem nuevoInstancias;
    private javax.swing.JMenuItem nuevoProyecto;
    private javax.swing.JMenuItem nuevoTestCla;
    private javax.swing.JMenuItem nuevoTestInst;
    private javax.swing.JMenuItem nuevoTestReal;
    private javax.swing.JMenuItem nuevoTestRec;
    private javax.swing.JMenuItem nuevoTestSat;
    private javax.swing.JMenu nuevoTestSimple;
    private javax.swing.JMenuItem nuevoTestSparql;
    private javax.swing.JMenu proyectoMenu;
    private javax.swing.JMenuItem salirProyecto;
    private javax.swing.JMenu testsSimplesMenu;
    private javax.swing.JMenu testsSparqlMenu;
    private javax.swing.JMenuItem verInstancias;
    private javax.swing.JMenuItem verTestMenuItem;
    private javax.swing.JMenuItem verTestSparql;
    // End of variables declaration//GEN-END:variables

}
