/*
 * GroupTestQueryJPanel.java
 *
 * Created on 29 de mayo de 2008, 9:02
 */

package ontologytestgui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.ListIterator;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.CollectionTest;
import model.PropertyInstances;
import model.ClassInstances;
import model.QueryOntology;
import model.ScenarioTest;
import model.SparqlQueryOntology;

/**
 *
 * @author  sara.garcia
 */
public class GroupTestsJPanel extends javax.swing.JPanel {

    static final int desktopWidth = 700;
    static final int desktopHeight = 600;
    static JFrame frame;
    public static ArrayList<ScenarioTest> getScenarioTestCollection() {
        return scenarioTestCollection;
    }
    public static void setScenarioTestCollection(ArrayList<ScenarioTest> aScenarioTestCollection) {
        scenarioTestCollection = aScenarioTestCollection;
    }
    private AddInstancesJPanel addInstances;
    private static ArrayList<ScenarioTest> scenarioTestCollection;
    private int aux=0;
    
    /** Creates new form GroupTestQueryJPanel */
    public GroupTestsJPanel(int num) {
        initComponents(); 
        contentPanel.setLayout(new BorderLayout());
        contentPanel.setPreferredSize(new Dimension(desktopWidth, desktopHeight));
        
        testInstPanel.setLayout(new BoxLayout(testInstPanel, BoxLayout.Y_AXIS));
        testRetPanel.setLayout(new BoxLayout(testRetPanel, BoxLayout.Y_AXIS));
        testRealPanel.setLayout(new BoxLayout(testRealPanel, BoxLayout.Y_AXIS));
        testSatPanel.setLayout(new BoxLayout(testSatPanel, BoxLayout.Y_AXIS));
        testClasPanel.setLayout(new BoxLayout(testClasPanel, BoxLayout.Y_AXIS));
        
        for (int i = 0; i <= num; i++) {
            testInstPanel.add(new TestInstancesTFJPanel());
            testRetPanel.add(new TestInstancesQueryJPanel());
            testRealPanel.add(new TestInstancesQueryJPanel());
            testSatPanel.add(new TestInstancesQueryJPanel());
            testClasPanel.add(new TestInstancesTFJPanel());
        }

        scenarioTestCollection = new ArrayList<ScenarioTest>(4);
        for(int i=0;i<5;i++){
            scenarioTestCollection.add(new ScenarioTest());
        }
        addInstances = new AddInstancesJPanel(this);
        AddTestsJPanel addTests = new AddTestsJPanel();
        contentPanel.add(addTests,BorderLayout.NORTH);
        contentPanel.add(testsTabbedPane,BorderLayout.CENTER);
        contentPanel.add(addInstances,BorderLayout.SOUTH);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        testsTabbedPane = new javax.swing.JTabbedPane();
        test1ScrollPane = new javax.swing.JScrollPane();
        testInstPanel = new javax.swing.JPanel();
        test2ScrollPane = new javax.swing.JScrollPane();
        testRetPanel = new javax.swing.JPanel();
        test3ScrollPane = new javax.swing.JScrollPane();
        testRealPanel = new javax.swing.JPanel();
        test4ScrollPane = new javax.swing.JScrollPane();
        testSatPanel = new javax.swing.JPanel();
        test5ScrollPane = new javax.swing.JScrollPane();
        testClasPanel = new javax.swing.JPanel();
        guardarButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cancelarButton = new javax.swing.JButton();

        setName("GroupTestsJPanel"); // NOI18N

        javax.swing.GroupLayout testInstPanelLayout = new javax.swing.GroupLayout(testInstPanel);
        testInstPanel.setLayout(testInstPanelLayout);
        testInstPanelLayout.setHorizontalGroup(
            testInstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );
        testInstPanelLayout.setVerticalGroup(
            testInstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        test1ScrollPane.setViewportView(testInstPanel);
        testInstPanel.getAccessibleContext().setAccessibleName("0");

        testsTabbedPane.addTab("Instanciación", test1ScrollPane);

        javax.swing.GroupLayout testRetPanelLayout = new javax.swing.GroupLayout(testRetPanel);
        testRetPanel.setLayout(testRetPanelLayout);
        testRetPanelLayout.setHorizontalGroup(
            testRetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );
        testRetPanelLayout.setVerticalGroup(
            testRetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        test2ScrollPane.setViewportView(testRetPanel);
        testRetPanel.getAccessibleContext().setAccessibleName("1");

        testsTabbedPane.addTab("Retrieval", test2ScrollPane);

        javax.swing.GroupLayout testRealPanelLayout = new javax.swing.GroupLayout(testRealPanel);
        testRealPanel.setLayout(testRealPanelLayout);
        testRealPanelLayout.setHorizontalGroup(
            testRealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );
        testRealPanelLayout.setVerticalGroup(
            testRealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        test3ScrollPane.setViewportView(testRealPanel);

        testsTabbedPane.addTab("Realización", test3ScrollPane);

        javax.swing.GroupLayout testSatPanelLayout = new javax.swing.GroupLayout(testSatPanel);
        testSatPanel.setLayout(testSatPanelLayout);
        testSatPanelLayout.setHorizontalGroup(
            testSatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );
        testSatPanelLayout.setVerticalGroup(
            testSatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        test4ScrollPane.setViewportView(testSatPanel);

        testsTabbedPane.addTab("Satisfactibilidad", test4ScrollPane);

        javax.swing.GroupLayout testClasPanelLayout = new javax.swing.GroupLayout(testClasPanel);
        testClasPanel.setLayout(testClasPanelLayout);
        testClasPanelLayout.setHorizontalGroup(
            testClasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );
        testClasPanelLayout.setVerticalGroup(
            testClasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        test5ScrollPane.setViewportView(testClasPanel);

        testsTabbedPane.addTab("Clasificación", test5ScrollPane);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testsTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                .addContainerGap())
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(816, Short.MAX_VALUE)
                .addComponent(cancelarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarButton)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(599, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarButton)
                    .addComponent(cancelarButton))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName("GroupTestsJPanel");
    }// </editor-fold>//GEN-END:initComponents

private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
// TODO add your handling code here

    this.asociarInstancias();
    
    scenarioTestCollection.get(0).setTestName("Instanciación");
    scenarioTestCollection.get(1).setTestName("Retrieval");
    scenarioTestCollection.get(2).setTestName("Realización");
    scenarioTestCollection.get(3).setTestName("Satisfactibilidad");
    scenarioTestCollection.get(4).setTestName("Clasificación");
    
    if(aux==1){
        JOptionPane.showMessageDialog(frame,"Ambos campos CONSULTA y RESULTADO ESPERADO " +
                "son obligatorios. No puede dejar sólo uno de ellos en blanco",
                "Warning Message",JOptionPane.WARNING_MESSAGE);
    }else{
        CollectionTest collectionTest = new CollectionTest();
    
        collectionTest.setScenariotest(scenarioTestCollection);
        ArrayList<ScenarioTest> st = collectionTest.getScenariotest();
        ScenarioTest scenario = new ScenarioTest();
        QueryOntology query = new QueryOntology();
        ClassInstances clasinstances = new ClassInstances();
        PropertyInstances propinstances = new PropertyInstances();
        ListIterator lscenario,larrayclas,larrayprop,lquery;
        lscenario = st.listIterator();
        while(lscenario.hasNext()){
            scenario = (ScenarioTest) lscenario.next();
            if(!this.isScenarioEmpty(scenario)){
                String nombre = scenario.getTestName();
                System.out.println("Nombre del test: " +nombre);
                ArrayList<QueryOntology> qo = scenario.getQueryTest();
                ArrayList<ClassInstances> clin = scenario.getClassInstances();
                ArrayList<PropertyInstances> prin = scenario.getPropertyInstances();
                larrayclas = clin.listIterator();
                larrayprop = prin.listIterator();
                lquery = qo.listIterator();
                while(lquery.hasNext()){
                    query = (QueryOntology) lquery.next();
                    if(query!=null){
                        String q = query.getQuery();
                        String res = query.getResultexpected();
                        String com = query.getComment();
                        System.out.println("Query: "+q);
                        System.out.println("Result: "+res);
                        System.out.println("Comentario: "+com);
                    }
                }
                while(larrayclas.hasNext()){
                    clasinstances = (ClassInstances) larrayclas.next();
                    if(clasinstances!=null){
                        System.out.println("Query clase: " +clasinstances.getClassInstance());
                        System.out.println("Coment clase: " +clasinstances.getComment());
                    }
                }
                while(larrayprop.hasNext()){
                    propinstances = (PropertyInstances) larrayprop.next();
                    if(propinstances!=null){
                        System.out.println("Query prop: " +propinstances.getPropertyInstance());
                        System.out.println("Coment prop: " +propinstances.getComment());
                    }
                }
            System.out.println("--------");
            }
        }
    this.setVisible(false);
    System.exit(0);
    }
}//GEN-LAST:event_guardarButtonActionPerformed

private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    System.exit(0);
}//GEN-LAST:event_cancelarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton guardarButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane test1ScrollPane;
    private javax.swing.JScrollPane test2ScrollPane;
    private javax.swing.JScrollPane test3ScrollPane;
    private javax.swing.JScrollPane test4ScrollPane;
    private javax.swing.JScrollPane test5ScrollPane;
    private javax.swing.JPanel testClasPanel;
    private javax.swing.JPanel testInstPanel;
    private javax.swing.JPanel testRealPanel;
    private javax.swing.JPanel testRetPanel;
    private javax.swing.JPanel testSatPanel;
    private javax.swing.JTabbedPane testsTabbedPane;
    // End of variables declaration//GEN-END:variables

    private static void createAndShowGUI() {
        //JFrame.setDefaultLookAndFeelDecorated(true);
        frame = new JFrame("Test de Prueba");
        frame.getContentPane().add(new GroupTestsJPanel(25)); 
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                createAndShowGUI();
            }
        });
    }

    public JPanel getTestClasPanel() {
        return testClasPanel;
    }

    public JPanel getTestInstPanel() {
        return testInstPanel;
    }

    public JPanel getTestRealPanel() {
        return testRealPanel;
    }

    public JPanel getTestRetPanel() {
        return testRetPanel;
    }

    public JPanel getTestSatPanel() {
        return testSatPanel;
    }
    
    public int getSelectedTabed(){
        return testsTabbedPane.getSelectedIndex();
    }
    
    public boolean isScenarioEmpty(ScenarioTest scenarioTest){
            ArrayList<ClassInstances> classInstances = scenarioTest.getClassInstances();
            ArrayList<PropertyInstances> propertyInstances = scenarioTest.getPropertyInstances();
            ArrayList<QueryOntology> queryTest = scenarioTest.getQueryTest();
            ArrayList<SparqlQueryOntology> sparqlQuerys = scenarioTest.getSparqlQuerys();
            if(classInstances.isEmpty() && propertyInstances.isEmpty() && 
                    queryTest.isEmpty() && sparqlQuerys.isEmpty()){
                    return true;
            }else{
                return false;
            }
    }
    
    public void asociarInstancias(){
       
    aux=0;
    ArrayList<QueryOntology> queryTest1 = new ArrayList<QueryOntology>();
    ArrayList<QueryOntology> queryTest2 = new ArrayList<QueryOntology>();
    ArrayList<QueryOntology> queryTest3 = new ArrayList<QueryOntology>();
    ArrayList<QueryOntology> queryTest4 = new ArrayList<QueryOntology>();
    ArrayList<QueryOntology> queryTest5 = new ArrayList<QueryOntology>();
    
    JPanel panelInst = this.getTestInstPanel();
    int totalInst = panelInst.getComponentCount();
    JPanel panelClas = this.getTestClasPanel();
    int totalClas = panelClas.getComponentCount();
    JPanel panelReal = this.getTestRealPanel();
    int totalReal = panelReal.getComponentCount();
    JPanel panelRet = this.getTestRetPanel();
    int totalRet = panelRet.getComponentCount();
    JPanel panelSat = this.getTestSatPanel();
    int totalSat = panelSat.getComponentCount();

    for(int i=0;i<totalInst;i++){
        TestInstancesTFJPanel test = (TestInstancesTFJPanel) panelInst.getComponent(i);
        String query = test.getQuery();
        String resExpT = test.isTestTrue();
        String resExpF = test.isTestFalse();
        AddComentJDialog comentPane = test.getComment();
        String coment = comentPane.getComent();
        if(!query.equals("") && !resExpT.equals(resExpF)){
            QueryOntology testQuery = new QueryOntology(query,resExpT,coment);
            queryTest1.add(testQuery);
            scenarioTestCollection.get(0).setQueryTest(queryTest1);
        }else if((!query.equals("") && resExpT.equals(resExpF)) || ((query.equals("") && !resExpT.equals(resExpF)))){
            aux=1;
        }
    }

    for(int i=0;i<totalRet;i++){
        TestInstancesQueryJPanel test = (TestInstancesQueryJPanel) panelRet.getComponent(i);
        String query = test.getQuery();
        String queryExp = test.getQueryResult();
        AddComentJDialog comentPane = test.getComment();
        String coment = comentPane.getComent();
        if(!query.equals("") && !queryExp.equals("")){
            QueryOntology testQuery = new QueryOntology(query,queryExp,coment);
            queryTest2.add(testQuery);
            scenarioTestCollection.get(1).setQueryTest(queryTest2);
        }else if((!query.equals("") && queryExp.equals("")) || (query.equals("") && !queryExp.equals(""))){
            aux=1;
        }
    }

    for(int i=0;i<totalReal;i++){
        TestInstancesQueryJPanel test = (TestInstancesQueryJPanel) panelReal.getComponent(i);
        String query = test.getQuery();
        String queryExp = test.getQueryResult();
        AddComentJDialog comentPane = test.getComment();
        String coment = comentPane.getComent();
        if(!query.equals("") && !queryExp.equals("")){
            QueryOntology testQuery = new QueryOntology(query,queryExp,coment);
            queryTest3.add(testQuery);
            scenarioTestCollection.get(2).setQueryTest(queryTest3);
        }else if((!query.equals("") && queryExp.equals("")) || (query.equals("") && !queryExp.equals(""))){
            aux=1;
        }
    }
    for(int i=0;i<totalSat;i++){
        TestInstancesQueryJPanel test = (TestInstancesQueryJPanel) panelSat.getComponent(i);
        String query = test.getQuery();
        String queryExp = test.getQueryResult();
        AddComentJDialog comentPane = test.getComment();
        String coment = comentPane.getComent();
        if(!query.equals("") && !queryExp.equals("")){
            QueryOntology testQuery = new QueryOntology(query,queryExp,coment);
            queryTest4.add(testQuery);
            scenarioTestCollection.get(3).setQueryTest(queryTest4);
        }else if((!query.equals("") && queryExp.equals("")) || (query.equals("") && !queryExp.equals(""))){
            aux=1;
        }
    }
    for(int i=0;i<totalClas;i++){
        TestInstancesTFJPanel test = (TestInstancesTFJPanel) panelClas.getComponent(i);
        String query = test.getQuery();
        String resExpT = test.isTestTrue();
        String resExpF = test.isTestFalse();
        AddComentJDialog comentPane = test.getComment();
        String coment = comentPane.getComent();
        if(!query.equals("") && !resExpT.equals(resExpF)){
            QueryOntology testQuery = new QueryOntology(query,resExpT,coment);
            queryTest5.add(testQuery);
            scenarioTestCollection.get(4).setQueryTest(queryTest5);
        }else if((!query.equals("") && resExpT.equals(resExpF)) || ((query.equals("") && !resExpT.equals(resExpF)))){
            aux=1;
        }
    }
  }
}
